# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import reduce from functools, numpy and pandas
import re
import functools
import numpy as np
import pandas as pd

# Challenge 1 - Mapping

#### We will use the map function to clean up words in a book.

In the following cell, we will read a text file containing the book The Prophet by Khalil Gibran.

In [2]:
# Run this code:

location = '../data/58585-0.txt'
with open(location, 'r', encoding="utf8") as f:
    prophet = f.read().split(' ')

#### Let's remove the first 568 words since they contain information about the book but are not part of the book itself. 

Do this by removing from `prophet` elements 0 through 567 of the list (you can also do this by keeping elements 568 through the last element).

In [3]:
# your code here
#print(prophet)
new_book = enumerate(prophet,568)
list_book = (list(new_book))

If you look through the words, you will find that many words have a reference attached to them. For example, let's look at words 1 through 10.

In [4]:
# your code here
print(list_book)

[(568, '\ufeffThe'), (569, 'Project'), (570, 'Gutenberg'), (571, 'EBook'), (572, 'of'), (573, 'The'), (574, 'Prophet,'), (575, 'by'), (576, 'Kahlil'), (577, 'Gibran\n\nThis'), (578, 'eBook'), (579, 'is'), (580, 'for'), (581, 'the'), (582, 'use'), (583, 'of'), (584, 'anyone'), (585, 'anywhere'), (586, 'in'), (587, 'the'), (588, 'United'), (589, 'States'), (590, 'and\nmost'), (591, 'other'), (592, 'parts'), (593, 'of'), (594, 'the'), (595, 'world'), (596, 'at'), (597, 'no'), (598, 'cost'), (599, 'and'), (600, 'with'), (601, 'almost'), (602, 'no'), (603, 'restrictions\nwhatsoever.'), (604, ''), (605, 'You'), (606, 'may'), (607, 'copy'), (608, 'it,'), (609, 'give'), (610, 'it'), (611, 'away'), (612, 'or'), (613, 're-use'), (614, 'it'), (615, 'under'), (616, 'the'), (617, 'terms\nof'), (618, 'the'), (619, 'Project'), (620, 'Gutenberg'), (621, 'License'), (622, 'included'), (623, 'with'), (624, 'this'), (625, 'eBook'), (626, 'or'), (627, 'online'), (628, 'at\nwww.gutenberg.org.'), (629, ''), (630, 'If'), (631, 'you'), (632, 'are'), (633, 'not'), (634, 'located'), (635, 'in'), (636, 'the'), (637, 'United'), (638, 'States,'), (639, "you'll\nhave"), (640, 'to'), (641, 'check'), (642, 'the'), (643, 'laws'), (644, 'of'), (645, 'the'), (646, 'country'), (647, 'where'), (648, 'you'), (649, 'are'), (650, 'located'), (651, 'before'), (652, 'using\nthis'), (653, 'ebook.\n\n\n\nTitle:'), (654, 'The'), (655, 'Prophet\n\nAuthor:'), (656, 'Kahlil'), (657, 'Gibran\n\nRelease'), (658, 'Date:'), (659, 'January'), (660, '1,'), (661, '2019'), (662, '[EBook'), (663, '#58585]\nLast'), (664, 'Updated:'), (665, 'January'), (666, '3,'), (667, '2018\n\n\nLanguage:'), (668, 'English\n\nCharacter'), (669, 'set'), (670, 'encoding:'), (671, 'UTF-8\n\n***'), (672, 'START'), (673, 'OF'), (674, 'THIS'), (675, 'PROJECT'), (676, 'GUTENBERG'), (677, 'EBOOK'), (678, 'THE'), (679, 'PROPHET'), (680, '***\n\n\n\n\nProduced'), (681, 'by'), (682, 'David'), (683, 'Widger'), (684, 'from'), (685, 'page'), (686, 'images'), (687, 'generously\nprovided'), (688, 'by'), (689, 'the'), (690, 'Internet'), (691, "Archive\n\n\nTranscriber's"), (692, 'Note:'), (693, 'Page'), (694, 'numbers,'), (695, 'ie:'), (696, '{20},'), (697, 'are'), (698, 'included'), (699, 'in'), (700, 'this\nutf-8'), (701, 'text'), (702, 'file.'), (703, 'For'), (704, 'those'), (705, 'wishing'), (706, 'to'), (707, 'use'), (708, 'a'), (709, 'text'), (710, 'file'), (711, 'unencumbered\nwith'), (712, 'page'), (713, 'numbers'), (714, 'open'), (715, 'or'), (716, 'download'), (717, 'the'), (718, 'Latin-1'), (719, 'file'), (720, '58585-8.txt.\n\n\n\n\n\n\n\nTHE'), (721, 'PROPHET\n\nBy'), (722, 'Kahlil'), (723, 'Gibran\n\nNew'), (724, 'York:'), (725, 'Alfred'), (726, 'A.'), (727, 'Knopf\n\n1923\n\n_The'), (728, 'Twelve'), (729, 'Illustrations'), (730, 'In'), (731, 'This'), (732, 'Volume\nAre'), (733, 'Reproduced'), (734, 'From'), (735, 'Original'), (736, 'Drawings'), (737, 'By\nThe'), (738, 'Author_\n\n\n“His'), (739, 'power'), (740, 'came'), (741, 'from'), (742, 'some'), (743, 'great'), (744, 'reservoir\nof'), (745, 'spiritual'), (746, 'life'), (747, 'else'), (748, 'it'), (749, 'could'), (750, 'not'), (751, 'have\nbeen'), (752, 'so'), (753, 'universal'), (754, 'and'), (755, 'so'), (756, 'potent,'), (757, 'but'), (758, 'the\nmajesty'), (759, 'and'), (760, 'beauty'), (761, 'of'), (762, 'the'), (763, 'language'), (764, 'with\nwhich'), (765, 'he'), (766, 'clothed'), (767, 'it'), (768, 'were'), (769, 'all'), (770, 'his'), (771, 'own?”\n\n--Claude'), (772, 'Bragdon\n\n\nTHE'), (773, 'BOOKS'), (774, 'OF'), (775, 'KAHLIL'), (776, 'GIBRAN\n\nThe'), (777, 'Madman.'), (778, '1918'), (779, 'Twenty'), (780, 'Drawings.'), (781, '1919\nThe'), (782, 'Forerunner.'), (783, '1920'), (784, 'The'), (785, 'Prophet.'), (786, '1923\nSand'), (787, 'and'), (788, 'Foam.'), (789, '1926'), (790, 'Jesus'), (791, 'the'), (792, 'Son'), (793, 'of\nMan.'), (794, '1928'), (795, 'The'), (796, 'Forth'), (797, 'Gods.'), (798, '1931'), (799, 'The\nWanderer.'), (800, '1932'), (801, 'The'), (802, 'Garden'), (803, 'of'), (804, 'the'), (805, 'Prophet\n1933'), (806, 'Prose'), (807, 'Poems.'), (808, '1934'), (809, 'Nymphs'), (810, 'of'), (811, 'the\nValley.'), (812, '1948\n\n\n\n\nCONTENTS\n\n'), (813, ''), (814, ''), (815, ''), (816, ''), (817, ''), (818, ''), (819, ''), (820, ''), (821, ''), (822, 'The'), (823, 'Coming'), (824, 'of'), (825, 'the'), (826, 'Ship.......7\n'), (827, ''), (828, ''), (829, ''), (830, ''), (831, ''), (832, ''), (833, ''), (834, ''), (835, ''), (836, 'On'), (837, 'Love.....................15\n'), (838, ''), (839, ''), (840, ''), (841, ''), (842, ''), (843, ''), (844, ''), (845, ''), (846, ''), (847, 'On'), (848, 'Marriage.................19\n'), (849, ''), (850, ''), (851, ''), (852, ''), (853, ''), (854, ''), (855, ''), (856, ''), (857, ''), (858, 'On'), (859, 'Children.................21\n'), (860, ''), (861, ''), (862, ''), (863, ''), (864, ''), (865, ''), (866, ''), (867, ''), (868, ''), (869, 'On'), (870, 'Giving...................23\n'), (871, ''), (872, ''), (873, ''), (874, ''), (875, ''), (876, ''), (877, ''), (878, ''), (879, ''), (880, 'On'), (881, 'Eating'), (882, 'and'), (883, 'Drinking......27\n'), (884, ''), (885, ''), (886, ''), (887, ''), (888, ''), (889, ''), (890, ''), (891, ''), (892, ''), (893, 'On'), (894, 'Work.....................31\n'), (895, ''), (896, ''), (897, ''), (898, ''), (899, ''), (900, ''), (901, ''), (902, ''), (903, ''), (904, 'On'), (905, 'Joy'), (906, 'and'), (907, 'Sorrow...........33\n'), (908, ''), (909, ''), (910, ''), (911, ''), (912, ''), (913, ''), (914, ''), (915, ''), (916, ''), (917, 'On'), (918, 'Houses...................37\n'), (919, ''), (920, ''), (921, ''), (922, ''), (923, ''), (924, ''), (925, ''), (926, ''), (927, ''), (928, 'On'), (929, 'Clothes..................41\n'), (930, ''), (931, ''), (932, ''), (933, ''), (934, ''), (935, ''), (936, ''), (937, ''), (938, ''), (939, 'On'), (940, 'Buying'), (941, 'and'), (942, 'Selling.......43\n'), (943, ''), (944, ''), (945, ''), (946, ''), (947, ''), (948, ''), (949, ''), (950, ''), (951, ''), (952, 'On'), (953, 'Crime'), (954, 'and'), (955, 'Punishment.....45\n'), (956, ''), (957, ''), (958, ''), (959, ''), (960, ''), (961, ''), (962, ''), (963, ''), (964, ''), (965, 'On'), (966, 'Laws.....................51\n'), (967, ''), (968, ''), (969, ''), (970, ''), (971, ''), (972, ''), (973, ''), (974, ''), (975, ''), (976, 'On'), (977, 'Freedom..................55\n'), (978, ''), (979, ''), (980, ''), (981, ''), (982, ''), (983, ''), (984, ''), (985, ''), (986, ''), (987, 'On'), (988, 'Reason'), (989, 'and'), (990, 'Passion.......57\n'), (991, ''), (992, ''), (993, ''), (994, ''), (995, ''), (996, ''), (997, ''), (998, ''), (999, ''), (1000, 'On'), (1001, 'Pain.....................60\n'), (1002, ''), (1003, ''), (1004, ''), (1005, ''), (1006, ''), (1007, ''), (1008, ''), (1009, ''), (1010, ''), (1011, 'On'), (1012, 'Self-Knowledge...........62\n'), (1013, ''), (1014, ''), (1015, ''), (1016, ''), (1017, ''), (1018, ''), (1019, ''), (1020, ''), (1021, ''), (1022, 'On'), (1023, 'Teaching.................64\n'), (1024, ''), (1025, ''), (1026, ''), (1027, ''), (1028, ''), (1029, ''), (1030, ''), (1031, ''), (1032, ''), (1033, 'On'), (1034, 'Friendship...............66\n'), (1035, ''), (1036, ''), (1037, ''), (1038, ''), (1039, ''), (1040, ''), (1041, ''), (1042, ''), (1043, ''), (1044, 'On'), (1045, 'Talking..................68\n'), (1046, ''), (1047, ''), (1048, ''), (1049, ''), (1050, ''), (1051, ''), (1052, ''), (1053, ''), (1054, ''), (1055, 'On'), (1056, 'Time.....................70\n'), (1057, ''), (1058, ''), (1059, ''), (1060, ''), (1061, ''), (1062, ''), (1063, ''), (1064, ''), (1065, ''), (1066, 'On'), (1067, 'Good'), (1068, 'and'), (1069, 'Evil............72\n'), (1070, ''), (1071, ''), (1072, ''), (1073, ''), (1074, ''), (1075, ''), (1076, ''), (1077, ''), (1078, ''), (1079, 'On'), (1080, 'Prayer...................76\n'), (1081, ''), (1082, ''), (1083, ''), (1084, ''), (1085, ''), (1086, ''), (1087, ''), (1088, ''), (1089, ''), (1090, 'On'), (1091, 'Pleasure.................79\n'), (1092, ''), (1093, ''), (1094, ''), (1095, ''), (1096, ''), (1097, ''), (1098, ''), (1099, ''), (1100, ''), (1101, 'On'), (1102, 'Beauty...................83\n'), (1103, ''), (1104, ''), (1105, ''), (1106, ''), (1107, ''), (1108, ''), (1109, ''), (1110, ''), (1111, ''), (1112, 'On'), (1113, 'Religion.................87\n'), (1114, ''), (1115, ''), (1116, ''), (1117, ''), (1118, ''), (1119, ''), (1120, ''), (1121, ''), (1122, ''), (1123, 'On'), (1124, 'Death....................90\n'), (1125, ''), (1126, ''), (1127, ''), (1128, ''), (1129, ''), (1130, ''), (1131, ''), (1132, ''), (1133, ''), (1134, 'The'), (1135, 'Farewell................92\n\n\n\n\nTHE'), (1136, 'PROPHET\n\n|Almustafa,'), (1137, 'the{7}'), (1138, 'chosen'), (1139, 'and'), (1140, 'the\nbeloved,'), (1141, 'who'), (1142, 'was'), (1143, 'a'), (1144, 'dawn'), (1145, 'unto'), (1146, 'his'), (1147, 'own\nday,'), (1148, 'had'), (1149, 'waited'), (1150, 'twelve'), (1151, 'years'), (1152, 'in'), (1153, 'the'), (1154, 'city\nof'), (1155, 'Orphalese'), (1156, 'for'), (1157, 'his'), (1158, 'ship'), (1159, 'that'), (1160, 'was'), (1161, 'to\nreturn'), (1162, 'and'), (1163, 'bear'), (1164, 'him'), (1165, 'back'), (1166, 'to'), (1167, 'the'), (1168, 'isle'), (1169, 'of\nhis'), (1170, 'birth.\n\nAnd'), (1171, 'in'), (1172, 'the'), (1173, 'twelfth'), (1174, 'year,'), (1175, 'on'), (1176, 'the'), (1177, 'seventh\nday'), (1178, 'of'), (1179, 'Ielool,'), (1180, 'the'), (1181, 'month'), (1182, 'of'), (1183, 'reaping,'), (1184, 'he\nclimbed'), (1185, 'the'), (1186, 'hill'), (1187, 'without'), (1188, 'the'), (1189, 'city'), (1190, 'walls\nand'), (1191, 'looked'), (1192, 'seaward;'), (1193, 'and'), (1194, 'he'), (1195, 'beheld'), (1196, 'his\nship'), (1197, 'coming'), (1198, 'with'), (1199, 'the'), (1200, 'mist.\n\nThen'), (1201, 'the'), (1202, 'gates'), (1203, 'of'), (1204, 'his'), (1205, 'heart'), (1206, 'were'), (1207, 'flung\nopen,'), (1208, 'and'), (1209, 'his'), (1210, 'joy'), (1211, 'flew'), (1212, 'far'), (1213, 'over'), (1214, 'the'), (1215, 'sea.\nAnd'), (1216, 'he'), (1217, 'closed'), (1218, 'his'), (1219, 'eyes'), (1220, 'and'), (1221, 'prayed'), (1222, 'in'), (1223, 'the\nsilences'), (1224, 'of'), (1225, 'his'), (1226, 'soul.\n\n*****\n\nBut'), (1227, 'as'), (1228, 'he'), (1229, 'descended'), (1230, 'the'), (1231, 'hill,'), (1232, 'a'), (1233, 'sadness\ncame'), (1234, 'upon'), (1235, 'him,'), (1236, 'and'), (1237, 'he'), (1238, 'thought'), (1239, 'in'), (1240, 'his\nheart:\n\nHow'), (1241, 'shall'), (1242, 'I'), (1243, 'go'), (1244, 'in'), (1245, 'peace'), (1246, 'and'), (1247, 'without\nsorrow?'), (1248, 'Nay,'), (1249, 'not'), (1250, 'without'), (1251, 'a'), (1252, 'wound'), (1253, 'in'), (1254, 'the\nspirit'), (1255, 'shall'), (1256, 'I'), (1257, 'leave'), (1258, 'this'), (1259, 'city.'), (1260, '{8}Long\nwere'), (1261, 'the'), (1262, 'days'), (1263, 'of'), (1264, 'pain'), (1265, 'I'), (1266, 'have'), (1267, 'spent\nwithin'), (1268, 'its'), (1269, 'walls,'), (1270, 'and'), (1271, 'long'), (1272, 'were'), (1273, 'the\nnights'), (1274, 'of'), (1275, 'aloneness;'), (1276, 'and'), (1277, 'who'), (1278, 'can'), (1279, 'depart\nfrom'), (1280, 'his'), (1281, 'pain'), (1282, 'and'), (1283, 'his'), (1284, 'aloneness'), (1285, 'without\nregret?\n\nToo'), (1286, 'many'), (1287, 'fragments'), (1288, 'of'), (1289, 'the'), (1290, 'spirit'), (1291, 'have'), (1292, 'I\nscattered'), (1293, 'in'), (1294, 'these'), (1295, 'streets,'), (1296, 'and'), (1297, 'too'), (1298, 'many\nare'), (1299, 'the'), (1300, 'children'), (1301, 'of'), (1302, 'my'), (1303, 'longing'), (1304, 'that'), (1305, 'walk\nnaked'), (1306, 'among'), (1307, 'these'), (1308, 'hills,'), (1309, 'and'), (1310, 'I'), (1311, 'cannot\nwithdraw'), (1312, 'from'), (1313, 'them'), (1314, 'without'), (1315, 'a'), (1316, 'burden'), (1317, 'and\nan'), (1318, 'ache.\n\nIt'), (1319, 'is'), (1320, 'not'), (1321, 'a'), (1322, 'garment'), (1323, 'I'), (1324, 'cast'), (1325, 'off'), (1326, 'this\nday,'), (1327, 'but'), (1328, 'a'), (1329, 'skin'), (1330, 'that'), (1331, 'I'), (1332, 'tear'), (1333, 'with'), (1334, 'my'), (1335, 'own\nhands.\n\nNor'), (1336, 'is'), (1337, 'it'), (1338, 'a'), (1339, 'thought'), (1340, 'I'), (1341, 'leave'), (1342, 'behind'), (1343, 'me,\nbut'), (1344, 'a'), (1345, 'heart'), (1346, 'made'), (1347, 'sweet'), (1348, 'with'), (1349, 'hunger'), (1350, 'and\nwith'), (1351, 'thirst.\n\n*****\n\nYet'), (1352, 'I'), (1353, 'cannot'), (1354, 'tarry'), (1355, 'longer.\n\nThe'), (1356, 'sea'), (1357, 'that'), (1358, 'calls'), (1359, 'all'), (1360, 'things'), (1361, 'unto'), (1362, 'her\ncalls'), (1363, 'me,'), (1364, 'and'), (1365, 'I'), (1366, 'must'), (1367, 'embark.\n\nFor'), (1368, 'to'), (1369, 'stay,'), (1370, 'though'), (1371, 'the'), (1372, 'hours'), (1373, 'burn'), (1374, 'in\nthe'), (1375, 'night,'), (1376, 'is'), (1377, 'to'), (1378, 'freeze'), (1379, 'and'), (1380, 'crystallize\nand'), (1381, 'be'), (1382, 'bound'), (1383, 'in'), (1384, 'a'), (1385, 'mould.\n\nFain'), (1386, 'would'), (1387, 'I'), (1388, 'take'), (1389, 'with'), (1390, 'me'), (1391, 'all'), (1392, 'that'), (1393, 'is\nhere.'), (1394, 'But'), (1395, 'how'), (1396, 'shall'), (1397, 'I?\n\nA'), (1398, 'voice'), (1399, 'cannot'), (1400, 'carry'), (1401, 'the'), (1402, 'tongue'), (1403, 'and\n{9}the'), (1404, 'lips'), (1405, 'that'), (1406, 'gave'), (1407, 'it'), (1408, 'wings.'), (1409, 'Alone\nmust'), (1410, 'it'), (1411, 'seek'), (1412, 'the'), (1413, 'ether.\n\nAnd'), (1414, 'alone'), (1415, 'and'), (1416, 'without'), (1417, 'his'), (1418, 'nest'), (1419, 'shall'), (1420, 'the\neagle'), (1421, 'fly'), (1422, 'across'), (1423, 'the'), (1424, 'sun.\n\n*****\n\nNow'), (1425, 'when'), (1426, 'he'), (1427, 'reached'), (1428, 'the'), (1429, 'foot'), (1430, 'of'), (1431, 'the\nhill,'), (1432, 'he'), (1433, 'turned'), (1434, 'again'), (1435, 'towards'), (1436, 'the'), (1437, 'sea,\nand'), (1438, 'he'), (1439, 'saw'), (1440, 'his'), (1441, 'ship'), (1442, 'approaching'), (1443, 'the\nharbour,'), (1444, 'and'), (1445, 'upon'), (1446, 'her'), (1447, 'prow'), (1448, 'the'), (1449, 'mariners,\nthe'), (1450, 'men'), (1451, 'of'), (1452, 'his'), (1453, 'own'), (1454, 'land.\n\nAnd'), (1455, 'his'), (1456, 'soul'), (1457, 'cried'), (1458, 'out'), (1459, 'to'), (1460, 'them,'), (1461, 'and'), (1462, 'he\nsaid:\n\nSons'), (1463, 'of'), (1464, 'my'), (1465, 'ancient'), (1466, 'mother,'), (1467, 'you'), (1468, 'riders'), (1469, 'of\nthe'), (1470, 'tides,\n\nHow'), (1471, 'often'), (1472, 'have'), (1473, 'you'), (1474, 'sailed'), (1475, 'in'), (1476, 'my'), (1477, 'dreams.\nAnd'), (1478, 'now'), (1479, 'you'), (1480, 'come'), (1481, 'in'), (1482, 'my'), (1483, 'awakening,'), (1484, 'which\nis'), (1485, 'my'), (1486, 'deeper'), (1487, 'dream.\n\nReady'), (1488, 'am'), (1489, 'I'), (1490, 'to'), (1491, 'go,'), (1492, 'and'), (1493, 'my'), (1494, 'eagerness'), (1495, 'with\nsails'), (1496, 'full'), (1497, 'set'), (1498, 'awaits'), (1499, 'the'), (1500, 'wind.\n\nOnly'), (1501, 'another'), (1502, 'breath'), (1503, 'will'), (1504, 'I'), (1505, 'breathe'), (1506, 'in\nthis'), (1507, 'still'), (1508, 'air,'), (1509, 'only'), (1510, 'another'), (1511, 'loving'), (1512, 'look\ncast'), (1513, 'backward,\n\nAnd'), (1514, 'then'), (1515, 'I'), (1516, 'shall'), (1517, 'stand'), (1518, 'among'), (1519, 'you,'), (1520, 'a\nseafarer'), (1521, 'among'), (1522, 'seafarers.'), (1523, '{10}And'), (1524, 'you,\nvast'), (1525, 'sea,'), (1526, 'sleepless'), (1527, 'mother,\n\nWho'), (1528, 'alone'), (1529, 'are'), (1530, 'peace'), (1531, 'and'), (1532, 'freedom'), (1533, 'to'), (1534, 'the\nriver'), (1535, 'and'), (1536, 'the'), (1537, 'stream,\n\nOnly'), (1538, 'another'), (1539, 'winding'), (1540, 'will'), (1541, 'this'), (1542, 'stream\nmake,'), (1543, 'only'), (1544, 'another'), (1545, 'murmur'), (1546, 'in'), (1547, 'this'), (1548, 'glade,\n\nAnd'), (1549, 'then'), (1550, 'shall'), (1551, 'I'), (1552, 'come'), (1553, 'to'), (1554, 'you,'), (1555, 'a\nboundless'), (1556, 'drop'), (1557, 'to'), (1558, 'a'), (1559, 'boundless'), (1560, 'ocean.\n\n*****\n\nAnd'), (1561, 'as'), (1562, 'he'), (1563, 'walked'), (1564, 'he'), (1565, 'saw'), (1566, 'from'), (1567, 'afar'), (1568, 'men\nand'), (1569, 'women'), (1570, 'leaving'), (1571, 'their'), (1572, 'fields'), (1573, 'and'), (1574, 'their\nvineyards'), (1575, 'and'), (1576, 'hastening'), (1577, 'towards'), (1578, 'the'), (1579, 'city\ngates.\n\nAnd'), (1580, 'he'), (1581, 'heard'), (1582, 'their'), (1583, 'voices'), (1584, 'calling'), (1585, 'his\nname,'), (1586, 'and'), (1587, 'shouting'), (1588, 'from'), (1589, 'field'), (1590, 'to'), (1591, 'field\ntelling'), (1592, 'one'), (1593, 'another'), (1594, 'of'), (1595, 'the'), (1596, 'coming'), (1597, 'of'), (1598, 'his\nship.\n\nAnd'), (1599, 'he'), (1600, 'said'), (1601, 'to'), (1602, 'himself:\n\nShall'), (1603, 'the'), (1604, 'day'), (1605, 'of'), (1606, 'parting'), (1607, 'be'), (1608, 'the'), (1609, 'day'), (1610, 'of\ngathering?\n\nAnd'), (1611, 'shall'), (1612, 'it'), (1613, 'be'), (1614, 'said'), (1615, 'that'), (1616, 'my'), (1617, 'eve'), (1618, 'was'), (1619, 'in\ntruth'), (1620, 'my'), (1621, 'dawn?\n\nAnd'), (1622, 'what'), (1623, 'shall'), (1624, 'I'), (1625, 'give'), (1626, 'unto'), (1627, 'him'), (1628, 'who'), (1629, 'has\nleft'), (1630, 'his'), (1631, 'plough'), (1632, 'in'), (1633, 'midfurrow,'), (1634, 'or'), (1635, 'to\nhim'), (1636, 'who'), (1637, 'has'), (1638, 'stopped'), (1639, 'the'), (1640, 'wheel'), (1641, 'of'), (1642, 'his\nwinepress?'), (1643, '{11}Shall'), (1644, 'my'), (1645, 'heart'), (1646, 'become'), (1647, 'a\ntree'), (1648, 'heavy-laden'), (1649, 'with'), (1650, 'fruit'), (1651, 'that'), (1652, 'I'), (1653, 'may\ngather'), (1654, 'and'), (1655, 'give'), (1656, 'unto'), (1657, 'them?\n\nAnd'), (1658, 'shall'), (1659, 'my'), (1660, 'desires'), (1661, 'flow'), (1662, 'like'), (1663, 'a\nfountain'), (1664, 'that'), (1665, 'I'), (1666, 'may'), (1667, 'fill'), (1668, 'their'), (1669, 'cups?\n\nAm'), (1670, 'I'), (1671, 'a'), (1672, 'harp'), (1673, 'that'), (1674, 'the'), (1675, 'hand'), (1676, 'of'), (1677, 'the'), (1678, 'mighty\nmay'), (1679, 'touch'), (1680, 'me,'), (1681, 'or'), (1682, 'a'), (1683, 'flute'), (1684, 'that'), (1685, 'his'), (1686, 'breath\nmay'), (1687, 'pass'), (1688, 'through'), (1689, 'me?\n\nA'), (1690, 'seeker'), (1691, 'of'), (1692, 'silences'), (1693, 'am'), (1694, 'I,'), (1695, 'and'), (1696, 'what\ntreasure'), (1697, 'have'), (1698, 'I'), (1699, 'found'), (1700, 'in'), (1701, 'silences'), (1702, 'that'), (1703, 'I\nmay'), (1704, 'dispense'), (1705, 'with'), (1706, 'confidence?\n\nIf'), (1707, 'this'), (1708, 'is'), (1709, 'my'), (1710, 'day'), (1711, 'of'), (1712, 'harvest,'), (1713, 'in'), (1714, 'what\nfields'), (1715, 'have'), (1716, 'I'), (1717, 'sowed'), (1718, 'the'), (1719, 'seed,'), (1720, 'and'), (1721, 'in\nwhat'), (1722, 'unremembered'), (1723, 'seasons?\n\nIf'), (1724, 'this'), (1725, 'indeed'), (1726, 'be'), (1727, 'the'), (1728, 'hour'), (1729, 'in'), (1730, 'which'), (1731, 'I\nlift'), (1732, 'up'), (1733, 'my'), (1734, 'lantern,'), (1735, 'it'), (1736, 'is'), (1737, 'not'), (1738, 'my'), (1739, 'flame\nthat'), (1740, 'shall'), (1741, 'burn'), (1742, 'therein.\n\nEmpty'), (1743, 'and'), (1744, 'dark'), (1745, 'shall'), (1746, 'I'), (1747, 'raise'), (1748, 'my'), (1749, 'lantern,\n\nAnd'), (1750, 'the'), (1751, 'guardian'), (1752, 'of'), (1753, 'the'), (1754, 'night'), (1755, 'shall'), (1756, 'fill\nit'), (1757, 'with'), (1758, 'oil'), (1759, 'and'), (1760, 'he'), (1761, 'shall'), (1762, 'light'), (1763, 'it'), (1764, 'also.\n\n*****\n\nThese'), (1765, 'things'), (1766, 'he'), (1767, 'said'), (1768, 'in'), (1769, 'words.'), (1770, 'But'), (1771, 'much\nin'), (1772, 'his'), (1773, 'heart'), (1774, 'remained'), (1775, 'unsaid.'), (1776, 'For'), (1777, '{12}he\nhimself'), (1778, 'could'), (1779, 'not'), (1780, 'speak'), (1781, 'his'), (1

In [5]:
for x in range(1,10):
    print(list_book[x])

(569, 'Project')
(570, 'Gutenberg')
(571, 'EBook')
(572, 'of')
(573, 'The')
(574, 'Prophet,')
(575, 'by')
(576, 'Kahlil')
(577, 'Gibran\n\nThis')

#### The next step is to create a function that will remove references. 

We will do this by splitting the string on the `{` character and keeping only the part before this character. Write your function below.

In [6]:
def reference(x):
    '''
    Input: A string
    Output: The string with references removed
    
    Example:
    Input: 'the{7}'
    Output: 'the'
    '''

    
    x = re.sub(r'\{\d+\}',"", x) #This line replaces the '{number}' to ''
    print("Character without references: " + str(x))
    return x
    
    # your code here

In [7]:
reference("{101}Why")

Character without references: Why

'Why'

Now that we have our function, use the `map()` function to apply this function to our book, The Prophet. Return the resulting list to a new list called `prophet_reference`.

In [8]:
#print(list_book)
prophet_reference = []
for x in list_book:
    x = reference(x[1])
    prophet_reference.append(x)

print(prophet_reference)
print(type(prophet_reference))

Character without references: ﻿The
Character without references: Project
Character without references: Gutenberg
Character without references: EBook
Character without references: of
Character without references: The
Character without references: Prophet,
Character without references: by
Character without references: Kahlil
Character without references: Gibran

This
Character without references: eBook
Character without references: is
Character without references: for
Character without references: the
Character without references: use
Character without references: of
Character without references: anyone
Character without references: anywhere
Character without references: in
Character without references: the
Character without references: United
Character without references: States
Character without references: and
most
Character without references: other
Character without references: parts
Character without references: of
Character without references: the
Character without references: world
Character without references: at
Character without references: no
Character without references: cost
Character without references: and
Character without references: with
Character without references: almost
Character without references: no
Character without references: restrictions
whatsoever.
Character without references:
Character without references: You
Character without references: may
Character without references: copy
Character without references: it,
Character without references: give
Character without references: it
Character without references: away
Character without references: or
Character without references: re-use
Character without references: it
Character without references: under
Character without references: the
Character without references: terms
of
Character without references: the
Character without references: Project
Character without references: Gutenberg
Character without references: License
Character without references: included
Character without references: with
Character without references: this
Character without references: eBook
Character without references: or
Character without references: online
Character without references: at
www.gutenberg.org.
Character without references:
Character without references: If
Character without references: you
Character without references: are
Character without references: not
Character without references: located
Character without references: in
Character without references: the
Character without references: United
Character without references: States,
Character without references: you'll
have
Character without references: to
Character without references: check
Character without references: the
Character without references: laws
Character without references: of
Character without references: the
Character without references: country
Character without references: where
Character without references: you
Character without references: are
Character without references: located
Character without references: before
Character without references: using
this
Character without references: ebook.



Title:
Character without references: The
Character without references: Prophet

Author:
Character without references: Kahlil
Character without references: Gibran

Release
Character without references: Date:
Character without references: January
Character without references: 1,
Character without references: 2019
Character without references: [EBook
Character without references: #58585]
Last
Character without references: Updated:
Character without references: January
Character without references: 3,
Character without references: 2018


Language:
Character without references: English

Character
Character without references: set
Character without references: encoding:
Character without references: UTF-8

***
Character without references: START
Character without references: OF
Character without references: THIS
Character without references: PROJECT
Character without references: GUTENBERG
Character without references: EBOOK
Character without references: THE
Character without references: PROPHET
Character without references: ***




Produced
Character without references: by
Character without references: David
Character without references: Widger
Character without references: from
Character without references: page
Character without references: images
Character without references: generously
provided
Character without references: by
Character without references: the
Character without references: Internet
Character without references: Archive


Transcriber's
Character without references: Note:
Character without references: Page
Character without references: numbers,
Character without references: ie:
Character without references: ,
Character without references: are
Character without references: included
Character without references: in
Character without references: this
utf-8
Character without references: text
Character without references: file.
Character without references: For
Character without references: those
Character without references: wishing
Character without references: to
Character without references: use
Character without references: a
Character without references: text
Character without references: file
Character without references: unencumbered
with
Character without references: page
Character without references: numbers
Character without references: open
Character without references: or
Character without references: download
Character without references: the
Character without references: Latin-1
Character without references: file
Character without references: 58585-8.txt.







THE
Character without references: PROPHET

By
Character without references: Kahlil
Character without references: Gibran

New
Character without references: York:
Character without references: Alfred
Character without references: A.
Character without references: Knopf

1923

_The
Character without references: Twelve
Character without references: Illustrations
Character without references: In
Character without references: This
Character without references: Volume
Are
Character without references: Reproduced
Character without references: From
Character without references: Original
Character without references: Drawings
Character without references: By
The
Character without references: Author_


“His
Character without references: power
Character without references: came
Character without references: from
Character without references: some
Character without references: great
Character without references: reservoir
of
Character without references: spiritual
Character without references: life
Character without references: else
Character without references: it
Character without references: could
Character without references: not
Character without references: have
been
Character without references: so
Character without references: universal
Character without references: and
Character without references: so
Character without references: potent,
Character without references: but
Character without references: the
majesty
Character without references: and
Character without references: beauty
Character without references: of
Character without references: the
Character without references: language
Character without references: with
which
Character without references: he
Character without references: clothed
Character without references: it
Character without references: were
Character without references: all
Character without references: his
Character without references: own?”

--Claude
Character without references: Bragdon


THE
Character without references: BOOKS
Character without references: OF
Character without references: KAHLIL
Character without references: GIBRAN

The
Character without references: Madman.
Character without references: 1918
Character without references: Twenty
Character without references: Drawings.
Character without references: 1919
The
Character without references: Forerunner.
Character without references: 1920
Character without references: The
Character without references: Prophet.
Character without references: 1923
Sand
Character without references: and
Character without references: Foam.
Character without references: 1926
Character without references: Jesus
Character without references: the
Character without references: Son
Character without references: of
Man.
Character without references: 1928
Character without references: The
Character without references: Forth
Character without references: Gods.
Character without references: 1931
Character without references: The
Wanderer.
Character without references: 1932
Character without references: The
Character without references: Garden
Character without references: of
Character without references: the
Character without references: Prophet
1933
Character without references: Prose
Character without references: Poems.
Character without references: 1934
Character without references: Nymphs
Character without references: of
Character without references: the
Valley.
Character without references: 1948




CONTENTS


Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: The
Character without references: Coming
Character without references: of
Character without references: the
Character without references: Ship.......7

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Love.....................15

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Marriage.................19

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Children.................21

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Giving...................23

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Eating
Character without references: and
Character without references: Drinking......27

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Work.....................31

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Joy
Character without references: and
Character without references: Sorrow...........33

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Houses...................37

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Clothes..................41

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Buying
Character without references: and
Character without references: Selling.......43

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Crime
Character without references: and
Character without references: Punishment.....45

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Laws.....................51

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Freedom..................55

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Reason
Character without references: and
Character without references: Passion.......57

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Pain.....................60

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Self-Knowledge...........62

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Teaching.................64

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Friendship...............66

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Talking..................68

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Time.....................70

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Good
Character without references: and
Character without references: Evil............72

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Prayer...................76

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Pleasure.................79

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Beauty...................83

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Religion.................87

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: On
Character without references: Death....................90

Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references:
Character without references: The
Character without references: Farewell................92




THE
Character without references: PROPHET

|Almustafa,
Character without references: the
Character without references: chosen
Character without references: and
Character without references: the
beloved,
Character without references: who
Character without references: was
Character without references: a
Character without references: dawn

Another thing you may have noticed is that some words contain a line break. Let's write a function to split those words. Our function will return the string split on the character `\n`. Write your function in the cell below.

In [9]:
def line_break(x):
    '''
    Input: A string
    Output: A list of strings split on the line break (\n) character
        
    Example:
    Input: 'the\nbeloved'
    Output: ['the', 'beloved']

    
    '''
    x = x.split("\n")
    return x
    
    # your code here

In [10]:
line_break('the\nharbour,')

['the', 'harbour,']

Apply the `line_break` function to the `prophet_reference` list. Name the new list `prophet_line`.

In [11]:
# your code here
#print(list_book)
#print(prophet_reference)
prophet_line = []
for x in prophet_reference:
    x = line_break(x)
    prophet_line.append(x)

print(prophet_line)

[['\ufeffThe'], ['Project'], ['Gutenberg'], ['EBook'], ['of'], ['The'], ['Prophet,'], ['by'], ['Kahlil'], ['Gibran', '', 'This'], ['eBook'], ['is'], ['for'], ['the'], ['use'], ['of'], ['anyone'], ['anywhere'], ['in'], ['the'], ['United'], ['States'], ['and', 'most'], ['other'], ['parts'], ['of'], ['the'], ['world'], ['at'], ['no'], ['cost'], ['and'], ['with'], ['almost'], ['no'], ['restrictions', 'whatsoever.'], [''], ['You'], ['may'], ['copy'], ['it,'], ['give'], ['it'], ['away'], ['or'], ['re-use'], ['it'], ['under'], ['the'], ['terms', 'of'], ['the'], ['Project'], ['Gutenberg'], ['License'], ['included'], ['with'], ['this'], ['eBook'], ['or'], ['online'], ['at', 'www.gutenberg.org.'], [''], ['If'], ['you'], ['are'], ['not'], ['located'], ['in'], ['the'], ['United'], ['States,'], ["you'll", 'have'], ['to'], ['check'], ['the'], ['laws'], ['of'], ['the'], ['country'], ['where'], ['you'], ['are'], ['located'], ['before'], ['using', 'this'], ['ebook.', '', '', '', 'Title:'], ['The'], ['Prophet', '', 'Author:'], ['Kahlil'], ['Gibran', '', 'Release'], ['Date:'], ['January'], ['1,'], ['2019'], ['[EBook'], ['#58585]', 'Last'], ['Updated:'], ['January'], ['3,'], ['2018', '', '', 'Language:'], ['English', '', 'Character'], ['set'], ['encoding:'], ['UTF-8', '', '***'], ['START'], ['OF'], ['THIS'], ['PROJECT'], ['GUTENBERG'], ['EBOOK'], ['THE'], ['PROPHET'], ['***', '', '', '', '', 'Produced'], ['by'], ['David'], ['Widger'], ['from'], ['page'], ['images'], ['generously', 'provided'], ['by'], ['the'], ['Internet'], ['Archive', '', '', "Transcriber's"], ['Note:'], ['Page'], ['numbers,'], ['ie:'], [','], ['are'], ['included'], ['in'], ['this', 'utf-8'], ['text'], ['file.'], ['For'], ['those'], ['wishing'], ['to'], ['use'], ['a'], ['text'], ['file'], ['unencumbered', 'with'], ['page'], ['numbers'], ['open'], ['or'], ['download'], ['the'], ['Latin-1'], ['file'], ['58585-8.txt.', '', '', '', '', '', '', '', 'THE'], ['PROPHET', '', 'By'], ['Kahlil'], ['Gibran', '', 'New'], ['York:'], ['Alfred'], ['A.'], ['Knopf', '', '1923', '', '_The'], ['Twelve'], ['Illustrations'], ['In'], ['This'], ['Volume', 'Are'], ['Reproduced'], ['From'], ['Original'], ['Drawings'], ['By', 'The'], ['Author_', '', '', '“His'], ['power'], ['came'], ['from'], ['some'], ['great'], ['reservoir', 'of'], ['spiritual'], ['life'], ['else'], ['it'], ['could'], ['not'], ['have', 'been'], ['so'], ['universal'], ['and'], ['so'], ['potent,'], ['but'], ['the', 'majesty'], ['and'], ['beauty'], ['of'], ['the'], ['language'], ['with', 'which'], ['he'], ['clothed'], ['it'], ['were'], ['all'], ['his'], ['own?”', '', '--Claude'], ['Bragdon', '', '', 'THE'], ['BOOKS'], ['OF'], ['KAHLIL'], ['GIBRAN', '', 'The'], ['Madman.'], ['1918'], ['Twenty'], ['Drawings.'], ['1919', 'The'], ['Forerunner.'], ['1920'], ['The'], ['Prophet.'], ['1923', 'Sand'], ['and'], ['Foam.'], ['1926'], ['Jesus'], ['the'], ['Son'], ['of', 'Man.'], ['1928'], ['The'], ['Forth'], ['Gods.'], ['1931'], ['The', 'Wanderer.'], ['1932'], ['The'], ['Garden'], ['of'], ['the'], ['Prophet', '1933'], ['Prose'], ['Poems.'], ['1934'], ['Nymphs'], ['of'], ['the', 'Valley.'], ['1948', '', '', '', '', 'CONTENTS', '', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['The'], ['Coming'], ['of'], ['the'], ['Ship.......7', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Love.....................15', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Marriage.................19', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Children.................21', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Giving...................23', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Eating'], ['and'], ['Drinking......27', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Work.....................31', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Joy'], ['and'], ['Sorrow...........33', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Houses...................37', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Clothes..................41', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Buying'], ['and'], ['Selling.......43', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Crime'], ['and'], ['Punishment.....45', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Laws.....................51', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Freedom..................55', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Reason'], ['and'], ['Passion.......57', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Pain.....................60', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Self-Knowledge...........62', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Teaching.................64', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Friendship...............66', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Talking..................68', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Time.....................70', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Good'], ['and'], ['Evil............72', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Prayer...................76', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Pleasure.................79', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Beauty...................83', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Religion.................87', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Death....................90', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['The'], ['Farewell................92', '', '', '', '', 'THE'], ['PROPHET', '', '|Almustafa,'], ['the'], ['chosen'], ['and'], ['the', 'beloved,'], ['who'], ['was'], ['a'], ['dawn'], ['unto'], ['his'], ['own', 'day,'], ['had'], ['waited'], ['twelve'], ['years'], ['in'], ['the'], ['city', 'of'], ['Orphalese'], ['for'], ['his'], ['ship'], ['that'], ['was'], ['to', 'return'], ['and'], ['bear'], ['him'], ['back'], ['to'], ['the'], ['isle'], ['of', 'his'], ['birth.', '', 'And'], ['in'], ['the'], ['twelfth'], ['year,'], ['on'], ['the'], ['seventh', 'day'], ['of'], ['Ielool,'], ['the'], ['month'], ['of'], ['reaping,'], ['he', 'climbed'], ['the'], ['hill'], ['without'], ['the'], ['city'], ['walls', 'and'], ['looked'], ['seaward;'], ['and'], ['he'], ['beheld'], ['his', 'ship'], ['coming'], ['with'], ['the'], ['mist.', '', 'Then'], ['the'], ['gates'], ['of'], ['his'], ['heart'], ['were'], ['flung', 'open,'], ['and'], ['his'], ['joy'], ['flew'], ['far'], ['over'], ['the'], ['sea.', 'And'], ['he'], ['closed'], ['his'], ['eyes'], ['and'], ['prayed'], ['in'], ['the', 'silences'], ['of'], ['his'], ['soul.', '', '*****', '', 'But'], ['as'], ['he'], ['descended'], ['the'], ['hill,'], ['a'], ['sadness', 'came'], ['upon'], ['him,'], ['and'], ['he'], ['thought'], ['in'], ['his', 'heart:', '', 'How'], ['shall'], ['I'], ['go'], ['in'], ['peace'], ['and'], ['without', 'sorrow?'], ['Nay,'], ['not'], ['without'], ['a'], ['wound'], ['in'], ['the', 'spirit'], ['shall'], ['I'], ['leave'], ['this'], ['city.'], ['Long', 'were'], ['the'], ['days'], ['of'], ['pain'], ['I'], ['have'], ['spent', 'within'], ['its'], ['walls,'], ['and'], ['long'], ['were'], ['the', 'nights'], ['of'], ['aloneness;'], ['and'], ['who'], ['can'], ['depart', 'from'], ['his'], ['pain'], ['and'], ['his'], ['aloneness'], ['without', 'regret?', '', 'Too'], ['many'], ['fragments'], ['of'], ['the'], ['spirit'], ['have'], ['I', 'scattered'], ['in'], ['these'], ['streets,'], ['and'], ['too'], ['many', 'are'], ['the'], ['children'], ['of'], ['my'], ['longing'], ['that'], ['walk', 'naked'], ['among'], ['these'], ['hills,'], ['and'], ['I'], ['cannot', 'withdraw'], ['from'], ['them'], ['without'], ['a'], ['burden'], ['and', 'an'], ['ache.', '', 'It'], ['is'], ['not'], ['a'], ['garment'], ['I'], ['cast'], ['off'], ['this', 'day,'], ['but'], ['a'], ['skin'], ['that'], ['I'], ['tear'], ['with'], ['my'], ['own', 'hands.', '', 'Nor'], ['is'], ['it'], ['a'], ['thought'], ['I'], ['leave'], ['behind'], ['me,', 'but'], ['a'], ['heart'], ['made'], ['sweet'], ['with'], ['hunger'], ['and', 'with'], ['thirst.', '', '*****', '', 'Yet'], ['I'], ['cannot'], ['tarry'], ['longer.', '', 'The'], ['sea'], ['that'], ['calls'], ['all'], ['things'], ['unto'], ['her', 'calls'], ['me,'], ['and'], ['I'], ['must'], ['embark.', '', 'For'], ['to'], ['stay,'], ['though'], ['the'], ['hours'], ['burn'], ['in', 'the'], ['night,'], ['is'], ['to'], ['freeze'], ['and'], ['crystallize', 'and'], ['be'], ['bound'], ['in'], ['a'], ['mould.', '', 'Fain'], ['would'], ['I'], ['take'], ['with'], ['me'], ['all'], ['that'], ['is', 'here.'], ['But'], ['how'], ['shall'], ['I?', '', 'A'], ['voice'], ['cannot'], ['carry'], ['the'], ['tongue'], ['and', 'the'], ['lips'], ['that'], ['gave'], ['it'], ['wings.'], ['Alone', 'must'], ['it'], ['seek'], ['the'], ['ether.', '', 'And'], ['alone'], ['and'], ['without'], ['his'], ['nest'], ['shall'], ['the', 'eagle'], ['fly'], ['across'], ['the'], ['sun.', '', '*****', '', 'Now'], ['when'], ['he'], ['reached'], ['the'], ['foot'], ['of'], ['the', 'hill,'], ['he'], ['turned'], ['again'], ['towards'], ['the'], ['sea,', 'and'], ['he'], ['saw'], ['his'], ['ship'], ['approaching'], ['the', 'harbour,'], ['and'], ['upon'], ['her'], ['prow'], ['the'], ['mariners,', 'the'], ['men'], ['of'], ['his'], ['own'], ['land.', '', 'And'], ['his'], ['soul'], ['cried'], ['out'], ['to'], ['them,'], ['and'], ['he', 'said:', '', 'Sons'], ['of'], ['my'], ['ancient'], ['mother,'], ['you'], ['riders'], ['of', 'the'], ['tides,', '', 'How'], ['often'], ['have'], ['you'], ['sailed'], ['in'], ['my'], ['dreams.', 'And'], ['now'], ['you'], ['come'], ['in'], ['my'], ['awakening,'], ['which', 'is'], ['my'], ['deeper'], ['dream.', '', 'Ready'], ['am'], ['I'], ['to'], ['go,'], ['and'], ['my'], ['eagerness'], ['with', 'sails'], ['full'], ['set'], ['awaits'], ['the'], ['wind.', '', 'Only'], ['another'], ['breath'], ['will'], ['I'], ['breathe'], ['in', 'this'], ['still'], ['air,'], ['only'], ['another'], ['loving'], ['look', 'cast'], ['backward,', '', 'And'], ['then'], ['I'], ['shall'], ['stand'], ['among'], ['you,'], ['a', 'seafarer'], ['among'], ['seafarers.'], ['And'], ['you,', 'vast'], ['sea,'], ['sleepless'], ['mother,', '', 'Who'], ['alone'], ['are'], ['peace'], ['and'], ['freedom'], ['to'], ['the', 'river'], ['and'], ['the'], ['stream,', '', 'Only'], ['another'], ['winding'], ['will'], ['this'], ['stream', 'make,'], ['only'], ['another'], ['murmur'], ['in'], ['this'], ['glade,', '', 'And'], ['then'], ['shall'], ['I'], ['come'], ['to'], ['you,'], ['a', 'boundless'], ['drop'], ['to'], ['a'], ['boundless'], ['ocean.', '', '*****', '', 'And'], ['as'], ['he'], ['walked'], ['he'], ['saw'], ['from'], ['afar'], ['men', 'and'], ['women'], ['leaving'], ['their'], ['fields'], ['and'], ['their', 'vineyards'], ['and'], ['hastening'], ['towards'], ['the'], ['city', 'gates.', '', 'And'], ['he'], ['heard'], ['their'], ['voices'], ['calling'], ['his', 'name,'], ['and'], ['shouting'], ['from'], ['field'], ['to'], ['field', 'telling'], ['one'], ['another'], ['of'], ['the'], ['coming'], ['of'], ['his', 'ship.', '', 'And'], ['he'], ['said'], ['to'], ['himself:', '', 'Shall'], ['the'], ['day'], ['of'], ['parting'], ['be'], ['the'], ['day'], ['of', 'gathering?', '', 'And'], ['shall'], ['it'], ['be'], ['said'], ['that'], ['my'], ['eve'], ['was'], ['in', 'truth'], ['my'], ['dawn?', '', 'And'], ['what'], ['shall'], ['I'], ['give'], ['unto'], ['him'], ['who'], ['has', 'left'], ['his'], ['plough'], ['in'], ['midfurrow,'], ['or'], ['to', 'him'], ['who'], ['has'], ['stopped'], ['the'], ['wheel'], ['of'], ['his', 'winepress?'], ['Shall'], ['my'], ['heart'], ['become'], ['a', 'tree'], ['heavy-laden'], ['with'], ['fruit'], ['that'], ['I'], ['may', 'gather'], ['and'], ['give'], ['unto'], ['them?', '', 'And'], ['shall'], ['my'], ['desires'], ['flow'], ['like'], ['a', 'fountain'], ['that'], ['I'], ['may'], ['fill'], ['their'], ['cups?', '', 'Am'], ['I'], ['a'], ['harp'], ['that'], ['the'], ['hand'], ['of'], ['the'], ['mighty', 'may'], ['touch'], ['me,'], ['or'], ['a'], ['flute'], ['that'], ['his'], ['breath', 'may'], ['pass'], ['through'], ['me?', '', 'A'], ['seeker'], ['of'], ['silences'], ['am'], ['I,'], ['and'], ['what', 'treasure'], ['have'], ['I'], ['found'], ['in'], ['silences'], ['that'], ['I', 'may'], ['dispense'], ['with'], ['confidence?', '', 'If'], ['this'], ['is'], ['my'], ['day'], ['of'], ['harvest,'], ['in'], ['what', 'fields'], ['have'], ['I'], ['sowed'], ['the'], ['seed,'], ['and'], ['in', 'what'], ['unremembered'], ['seasons?', '', 'If'], ['this'], ['indeed'], ['be'], ['the'], ['hour'], ['in'], ['which'], ['I', 'lift'], ['up'], ['my'], ['lantern,'], ['it'], ['is'], ['not'], ['my'], ['flame', 'that'], ['shall'], ['burn'], ['therein.', '', 'Empty'], ['and'], ['dark'], ['shall'], ['I'], ['raise'], ['my'], ['lantern,', '', 'And'], ['the'], ['guardian'], ['of'], ['the'], ['night'], ['shall'], ['fill', 'it'], ['with'], ['oil'], ['and'], ['he'], ['shall'], ['light'], ['it'], ['also.', '', '*****', '', 'These'], ['things'], ['he'], ['said'], ['in'], ['words.'], ['But'], ['much', 'in'], ['his'], ['heart'], ['remained'], ['unsaid.'], ['For'], ['he', 'himself'], ['could'], ['not'], ['speak'], ['his'], ['deeper', 'secret.', '', '*****', '', '[Illustration:'], ['0020]', '', 'And'], ['when'], ['he'], ['entered'], ['into'], ['the'], ['city'], ['all', 'the'], ['people'], ['came'], ['to'], ['meet'], ['him,'], ['and'], ['they', 'were'], ['crying'], ['out'], ['to'], ['him'], ['as'], ['with'], ['one', 'voice.', '', 'And'], ['the'], ['elders'], ['of'], ['the'], ['city'], ['stood'], ['forth', 'and'], ['said:', '', 'Go'], ['not'], ['yet'], ['away'], ['from'], ['us.', '', 'A'], ['noontide'], ['have'], ['you'], ['been'], ['in'], ['our', 'twilight,'], ['and'], ['your'], ['youth'], ['has'], ['given'], ['us', 'dreams'], ['to'], ['dream.', '', 'No'], ['stranger'], ['are'], ['you'], ['among'], ['us,'], ['nor', 'a'], ['guest,'], ['but'], ['our'], ['son'], ['and'], ['our'], ['dearly', 'beloved.', '', 'Suffer'], ['not'], ['yet'], ['our'], ['eyes'], ['to'], ['hunger'], ['for', 'your'], ['face.', '', '*****', '', 'And'], ['the'], ['priests'], ['and'], ['the'], ['priestesses'], ['said', 'unto'], ['him:', '', 'Let'], ['not'], ['the'], ['waves'], ['of'], ['the'], ['sea'], ['separate'], ['us', 'now,'], ['and'], ['the'], ['years'], ['you'], ['have'], ['spent'], ['in'], ['our', 'midst'], ['become'], ['a'], ['memory.', '', 'You'], ['have'], ['walked'], ['among'], ['us'], ['a'], ['spirit,', 'and'], ['your'], ['shadow'], ['has'], ['been'], ['a'], ['light', 'upon'], ['our'], ['faces.', '', 'Much'], ['have'], ['we'], ['loved'], ['you.'], ['But'], ['speechless', 'was'], ['our'], ['love,'], ['and'], ['with'], ['veils'], ['has'], ['it'], ['been', 'veiled.', '', 'Yet'], ['now'], ['it'], ['cries'], ['aloud'], ['unto'], ['you,'], ['and', 'would'], ['stand'], ['revealed'], ['before'], ['you.', '', 'And'], ['ever'], ['has'], ['it'], ['been'], ['that'], ['love'], ['knows', 'not'], ['its'], ['own'], ['depth'], ['until'], ['the'], ['hour'], ['of', 'separation.', '', '*****', '', 'And'], ['others'], ['came'], ['also'], ['and'], ['entreated'], ['him.', 'But'], ['he'], ['answered'], ['them'], ['not.'], ['He'], ['only'], ['bent', 'his'], ['head;'], ['and'], ['those'], ['who'], ['stood'], ['near'], ['saw', 'his'], ['tears'], ['falling'], ['upon'], ['his'], ['breast.', '', 'And'], ['he'], ['and'], ['the'], ['people'], ['proceeded'], ['towards', 'the'], ['great'], ['square'], ['before'], ['the'], ['temple.', '', 'And'], ['there'], ['came'], ['out'], ['of'], ['the'], ['sanctuary'], ['a', 'woman'], ['whose'], ['name'], ['was'], ['Almitra.'], ['And'], ['she', 'was'], ['a'], ['seeress.', '', 'And'], ['he'], ['looked'], ['upon'], ['her'], ['with'], ['exceeding', 'tenderness,'], ['for'], ['it'], ['was'], ['she'], ['who'], ['had'], ['first', 'sought'], ['and'], ['believed'], ['in'], ['him'], ['when'], ['he'], ['had', 'been'], ['but'], ['a'], ['day'], ['in'], ['their'], ['city.'], ['And', 'she'], ['hailed'], ['him,'], ['saying:', '', 'Prophet'], ['of'], ['God,'], ['in'], ['quest'], ['of'], ['the', 'uttermost,'], ['long'], ['have'], ['you'], ['searched'], ['the', 'distances'], ['for'], ['your'], ['ship.', '', 'And'], ['now'], ['your'], ['ship'], ['has'], ['come,'], ['and'], ['you'], ['must', 'needs'], ['go.', '', 'Deep'], ['is'], ['your'], ['longing'], ['for'], ['the'], ['land'], ['of', 'your'], ['memories'], ['and'], ['the'], ['dwelling'], ['place', 'of'], ['your'], ['greater'], ['desires;'], ['and'], ['our'], ['love', 'would'], ['not'], ['bind'], ['you'], ['nor'], ['our'], ['needs'], ['hold', 'you.', '', 'Yet'], ['this'], ['we'], ['ask'], ['ere'], ['you'], ['leave'], ['us,'], ['that', 'you'], ['speak'], ['to'], ['us'], ['and'], ['give'], ['us'], ['of'], ['your', 'truth.', '', 'And'], ['we'], ['will'], ['give'], ['it'], ['unto'], ['our'], ['children,', 'and'], ['they'], ['unto'], ['their'], ['children,'], ['and'], ['it', 'shall'], ['not'], ['perish.', '', 'In'], ['your'], ['aloneness'], ['you'], ['have'], ['watched'], ['with', 'our'], ['days,'], ['and'], ['in'], ['your'], ['wakefulness'], ['you', 'have'], ['listened'], ['to'], ['the'], ['weeping'], ['and'], ['the', 'laughter'], ['of'], ['our'], ['sleep.', '', 'Now'], ['therefore'], ['disclose'], ['us'], ['to'], ['ourselves,', 'and'], ['tell'], ['us'], ['all'], ['that'], ['has'], ['been'], ['shown', 'you'], ['of'], ['that'], ['which'], ['is'], ['between'], ['birth'], ['and', 'death.', '', '*****', '', 'And'], ['he'], ['answered,', '', 'People'], ['of'], ['Orphalese,'], ['of'], ['what'], ['can'], ['I', 'speak'], ['save'], ['of'], ['that'], ['which'], ['is'], ['even'], ['now', 'moving'], ['within'], ['your'], ['souls?', '', '*****'], ['*****', '', 'Then'], ['said'], ['Almitra,'], ['Speak'], ['to'], ['us'], ['of', '_Love_.', '', 'And'], ['he'], ['raised'], ['his'], ['head'], ['and'], ['looked'], ['upon', 'the'], ['people,'], ['and'], ['there'], ['fell'], ['a'], ['stillness', 'upon'], ['them.'], ['And'], ['with'], ['a'], ['great'], ['voice'], ['he', 'said:', '', 'When'], ['love'], ['beckons'], ['to'], ['you,'], ['follow'], ['him,', '', 'Though'], ['his'], ['ways'], ['are'], ['hard'], ['and'], ['steep.', '', 'And'], ['when'], ['his'], ['wings'], ['enfold'], ['you'], ['yield'], ['to', 'him,', '', 'Though'], ['the'], ['sword'], ['hidden'], ['among'], ['his', 'pinions'], ['may'], ['wound'], ['you.', '', 'And'], ['when'], ['he'], ['speaks'], ['to'], ['you'], ['believe'], ['in', 'him,', '', 'Though'], ['his'], ['voice'], ['may'], ['shatter'], ['your'], ['dreams', 'as'], ['the'], ['north'], ['wind'], ['lays'], ['waste'], ['the'], ['garden.', '', 'For'], ['even'], ['as'], ['love'], ['crowns'], ['you'], ['so'], ['shall', 'he'], ['crucify'], ['you.'], ['Even'], ['as'], ['he'], ['is'], ['for'], ['your', 'growth'], ['so'], ['is'], ['he'], ['for'], ['your'], ['pruning.', '', 'Even'], ['as'], ['he'], ['ascends'], ['to'], ['your'], ['height'], ['and', 'caresses'], ['your'], ['tenderest'], ['branches', 'that'], ['quiver'], ['in'], ['the'], ['sun,', '', 'So'], ['shall'], ['he'], ['descend'], ['to'], ['your'], ['roots'], ['and', 'shake'], ['them'], ['in'], ['their'], ['clinging'], ['to'], ['the', 'earth.', '', '*****', '', 'Like'], ['sheaves'], ['of'], ['corn'], ['he'], ['gathers'], ['you'], ['unto', 'himself.', '', 'He'], ['threshes'], ['you'], ['to'], ['make'], ['you'], ['naked.', '', 'He'], ['sifts'], ['you'], ['to'], ['free'], ['you'], ['from'], ['your', 'husks.', '', 'He'], ['grinds'], ['you'], ['to'], ['whiteness.', '', 'He'], ['kn

If you look at the elements of `prophet_line`, you will see that the function returned lists and not strings. Our list is now a list of lists. Flatten the list using list comprehension. Assign this new list to `prophet_flat`.

In [12]:
# your code here

#Normal way
prophet_flat = []
for x in prophet_line:
    if len(x) > 1:
        for y in x:
            prophet_flat.append(y)

#prophet_flat = [new_x for x in prophet_line if x < 1 ]



print(prophet_flat)

['Gibran', '', 'This', 'and', 'most', 'restrictions', 'whatsoever.', 'terms', 'of', 'at', 'www.gutenberg.org.', "you'll", 'have', 'using', 'this', 'ebook.', '', '', '', 'Title:', 'Prophet', '', 'Author:', 'Gibran', '', 'Release', '#58585]', 'Last', '2018', '', '', 'Language:', 'English', '', 'Character', 'UTF-8', '', '***', '***', '', '', '', '', 'Produced', 'generously', 'provided', 'Archive', '', '', "Transcriber's", 'this', 'utf-8', 'unencumbered', 'with', '58585-8.txt.', '', '', '', '', '', '', '', 'THE', 'PROPHET', '', 'By', 'Gibran', '', 'New', 'Knopf', '', '1923', '', '_The', 'Volume', 'Are', 'By', 'The', 'Author_', '', '', '“His', 'reservoir', 'of', 'have', 'been', 'the', 'majesty', 'with', 'which', 'own?”', '', '--Claude', 'Bragdon', '', '', 'THE', 'GIBRAN', '', 'The', '1919', 'The', '1923', 'Sand', 'of', 'Man.', 'The', 'Wanderer.', 'Prophet', '1933', 'the', 'Valley.', '1948', '', '', '', '', 'CONTENTS', '', '', 'Ship.......7', '', 'Love.....................15', '', 'Marriage.................19', '', 'Children.................21', '', 'Giving...................23', '', 'Drinking......27', '', 'Work.....................31', '', 'Sorrow...........33', '', 'Houses...................37', '', 'Clothes..................41', '', 'Selling.......43', '', 'Punishment.....45', '', 'Laws.....................51', '', 'Freedom..................55', '', 'Passion.......57', '', 'Pain.....................60', '', 'Self-Knowledge...........62', '', 'Teaching.................64', '', 'Friendship...............66', '', 'Talking..................68', '', 'Time.....................70', '', 'Evil............72', '', 'Prayer...................76', '', 'Pleasure.................79', '', 'Beauty...................83', '', 'Religion.................87', '', 'Death....................90', '', 'Farewell................92', '', '', '', '', 'THE', 'PROPHET', '', '|Almustafa,', 'the', 'beloved,', 'own', 'day,', 'city', 'of', 'to', 'return', 'of', 'his', 'birth.', '', 'And', 'seventh', 'day', 'he', 'climbed', 'walls', 'and', 'his', 'ship', 'mist.', '', 'Then', 'flung', 'open,', 'sea.', 'And', 'the', 'silences', 'soul.', '', '*****', '', 'But', 'sadness', 'came', 'his', 'heart:', '', 'How', 'without', 'sorrow?', 'the', 'spirit', 'Long', 'were', 'spent', 'within', 'the', 'nights', 'depart', 'from', 'without', 'regret?', '', 'Too', 'I', 'scattered', 'many', 'are', 'walk', 'naked', 'cannot', 'withdraw', 'and', 'an', 'ache.', '', 'It', 'this', 'day,', 'own', 'hands.', '', 'Nor', 'me,', 'but', 'and', 'with', 'thirst.', '', '*****', '', 'Yet', 'longer.', '', 'The', 'her', 'calls', 'embark.', '', 'For', 'in', 'the', 'crystallize', 'and', 'mould.', '', 'Fain', 'is', 'here.', 'I?', '', 'A', 'and', 'the', 'Alone', 'must', 'ether.', '', 'And', 'the', 'eagle', 'sun.', '', '*****', '', 'Now', 'the', 'hill,', 'sea,', 'and', 'the', 'harbour,', 'mariners,', 'the', 'land.', '', 'And', 'he', 'said:', '', 'Sons', 'of', 'the', 'tides,', '', 'How', 'dreams.', 'And', 'which', 'is', 'dream.', '', 'Ready', 'with', 'sails', 'wind.', '', 'Only', 'in', 'this', 'look', 'cast', 'backward,', '', 'And', 'a', 'seafarer', 'you,', 'vast', 'mother,', '', 'Who', 'the', 'river', 'stream,', '', 'Only', 'stream', 'make,', 'glade,', '', 'And', 'a', 'boundless', 'ocean.', '', '*****', '', 'And', 'men', 'and', 'their', 'vineyards', 'city', 'gates.', '', 'And', 'his', 'name,', 'field', 'telling', 'his', 'ship.', '', 'And', 'himself:', '', 'Shall', 'of', 'gathering?', '', 'And', 'in', 'truth', 'dawn?', '', 'And', 'has', 'left', 'to', 'him', 'his', 'winepress?', 'a', 'tree', 'may', 'gather', 'them?', '', 'And', 'a', 'fountain', 'cups?', '', 'Am', 'mighty', 'may', 'breath', 'may', 'me?', '', 'A', 'what', 'treasure', 'I', 'may', 'confidence?', '', 'If', 'what', 'fields', 'in', 'what', 'seasons?', '', 'If', 'I', 'lift', 'flame', 'that', 'therein.', '', 'Empty', 'lantern,', '', 'And', 'fill', 'it', 'also.', '', '*****', '', 'These', 'much', 'in', 'he', 'himself', 'deeper', 'secret.', '', '*****', '', '[Illustration:', '0020]', '', 'And', 'all', 'the', 'they', 'were', 'one', 'voice.', '', 'And', 'forth', 'and', 'said:', '', 'Go', 'us.', '', 'A', 'our', 'twilight,', 'us', 'dreams', 'dream.', '', 'No', 'nor', 'a', 'dearly', 'beloved.', '', 'Suffer', 'for', 'your', 'face.', '', '*****', '', 'And', 'said', 'unto', 'him:', '', 'Let', 'us', 'now,', 'our', 'midst', 'memory.', '', 'You', 'spirit,', 'and', 'light', 'upon', 'faces.', '', 'Much', 'speechless', 'was', 'been', 'veiled.', '', 'Yet', 'and', 'would', 'you.', '', 'And', 'knows', 'not', 'of', 'separation.', '', '*****', '', 'And', 'him.', 'But', 'bent', 'his', 'saw', 'his', 'breast.', '', 'And', 'towards', 'the', 'temple.', '', 'And', 'a', 'woman', 'she', 'was', 'seeress.', '', 'And', 'exceeding', 'tenderness,', 'first', 'sought', 'had', 'been', 'And', 'she', 'saying:', '', 'Prophet', 'the', 'uttermost,', 'the', 'distances', 'ship.', '', 'And', 'must', 'needs', 'go.', '', 'Deep', 'of', 'your', 'place', 'of', 'love', 'would', 'hold', 'you.', '', 'Yet', 'that', 'you', 'your', 'truth.', '', 'And', 'children,', 'and', 'it', 'shall', 'perish.', '', 'In', 'with', 'our', 'you', 'have', 'the', 'laughter', 'sleep.', '', 'Now', 'ourselves,', 'and', 'shown', 'you', 'and', 'death.', '', '*****', '', 'And', 'answered,', '', 'People', 'I', 'speak', 'now', 'moving', 'souls?', '', '*****', '*****', '', 'Then', 'of', '_Love_.', '', 'And', 'upon', 'the', 'stillness', 'upon', 'he', 'said:', '', 'When', 'him,', '', 'Though', 'steep.', '', 'And', 'to', 'him,', '', 'Though', 'his', 'pinions', 'you.', '', 'And', 'in', 'him,', '', 'Though', 'dreams', 'as', 'garden.', '', 'For', 'shall', 'he', 'your', 'growth', 'pruning.', '', 'Even', 'and', 'caresses', 'branches', 'that', 'sun,', '', 'So', 'and', 'shake', 'the', 'earth.', '', '*****', '', 'Like', 'unto', 'himself.', '', 'He', 'naked.', '', 'He', 'your', 'husks.', '', 'He', 'whiteness.', '', 'He', 'pliant;', '', 'And', 'sacred', 'fire,', 'bread', 'for', 'feast.', '', '*****', '', 'All', 'you', 'that', 'your', 'heart,', 'a', 'fragment', 'heart.', '', 'But', 'only', 'love’s', 'pleasure,', '', 'Then', 'you', 'cover', 'of', 'love’s', 'threshing-floor,', '', 'Into', 'you', 'shall', 'your', 'laughter,', 'your', 'tears.', '', '*****', '', 'Love', 'takes', 'naught', 'itself.', '', 'Love', 'be', 'possessed;', '', 'For', 'love.', '', 'When', '“God', 'is', 'in', 'the', 'God.”', '', 'And', 'course', 'of', 'you', 'worthy,', 'course.', '', 'Love', 'fulfil', 'itself.', '', 'But', 'have', 'desires,', 'desires:', '', 'To', 'that', 'sings', 'To', 'know', 'tenderness.', '', 'To', 'understanding', 'of', 'love;', '', 'And', 'joyfully.', '', 'To', 'and', 'give', 'loving;', '', 'To', 'meditate', 'love’s', 'ecstacy;', '', 'To', 'with', 'gratitude;', '', 'And', 'for', 'the', 'of', 'praise', 'lips.', '', '[Illustration:', '0029]', '', '*****', '*****', '', 'Then', 'said,', 'And', 'master?', '', 'And', 'saying:', '', 'You', 'you', 'shall', 'forevermore.', '', 'You', 'white', 'wings', 'days.', '', 'Aye,', 'the', 'silent', 'God.', '', 'But', 'your', 'togetherness,', '', 'And', 'dance', 'between', 'you.', '', '*****', '', 'Love', 'of', 'love:', '', 'Let', 'between', 'the', 'souls.', '', 'Fill', 'from', 'one', 'cup.', '', 'Give', 'eat', 'not', 'and', 'dance', 'let', 'each', 'alone,', '', 'Even', 'alone', 'though', 'music.', '', '*****', '', 'Give', 'each', 'other’s', 'keeping.', '', 'For', 'contain', 'your', 'hearts.', '', 'And', 'near', 'together:', '', 'For', 'stand', 'apart,', '', 'And', 'grow', 'not', 'shadow.', '', '[Illustration:', '0032]', '', '*****', '*****', '', 'And', 'babe', 'against', 'of', '_Children_.', '', 'And', 'said:', '', 'Your', 'children.', '', 'They', 'of', 'Life’s', 'itself.', '', 'They', 'you,', '', 'And', 'they', 'belong', 'you.', '', '*****', '', 'You', 'your', 'thoughts,', '', 'For', 'thoughts.', '', 'You', 'their', 'souls,', '', 'For', 'of', 'tomorrow,', 'not', 'even', 'dreams.', '', 'You', 'seek', 'not', 'For', 'life', 'with', 'yesterday.', '', 'You', 'your', 'children', 'sent', 'forth.', '', 'The', 'path', 'of', 'with', 'His', 'swift', 'and', 'far.', '', 'Let', 'be', 'for', 'gladness;', '', 'For', 'that', 'flies,', 'is', 'stable.', '', '*****', '*****', '', 'Then', 'of', '_Giving_.', '', 'And', 'answered:', '', 'You', 'of', 'your', 'possessions.', '', 'It', 'you', 'truly', 'give.', '', 'For', 'things', 'you', 'need', 'them', 'tomorrow?', '', 'And', 'bring', 'to', 'bones', 'in', 'the', 'pilgrims', 'city?', '', 'And', 'need', 'itself?', '', 'Is', 'is', 'full,', 'unquenchable?', '', 'There', 'the', 'much', 'give', 'it', 'hidden', 'desire', 'unwholesome.', '', 'And', 'and', 'give', 'all.', '', 'These', 'and', 'the', 'is', 'never', 'empty.', '', 'There', 'and', 'that', 'reward.', '', 'And', 'pain,', 'and', 'baptism.', '', 'And', 'know', 'not', 'seek', 'joy,', 'of', 'virtue;', '', 'They', 'myrtle', 'breathes', 'space.', '', 'Through', 'God', 'speaks,', 'He', 'smiles', 'earth.', '', '[Illustration:', '0039]', '', 'It', 'it', 'is', 'through', 'understanding;', '', 'And', 'for', 'one', 'greater', 'than', 'giving.', '', 'And', 'withhold?', '', 'All', 'given;', '', 'Therefore', 'season', 'of', 'your', 'inheritors’.', '', 'You', 'only', 'to', 'deserving.”', '', 'The', 'so,', 'nor', 'pasture.', '', 'They', 'to', 'withhold', 'perish.', '', 'Surely', 'his', 'days', 'all', 'else', 'you.', '', 'And', 'from', 'the', 'his', 'cup', 'stream.', '', 'And', 'be,', 'than', 'courage', 'and', 'of', 'receiving?', '', 'And', 'rend', 'their', 'pride,', 'that', 'and', 'their', 'unabashed?', '', 'See', 'to', 'be', 'giving.', '', 'For', 'unto', 'life--while', 'a', 'giver,', 'witness.', '', 'And', 'are', 'all', 'of', 'gratitude,', 'upon', 'yourself', 'gives.', '', 'Rather', 'on', 'his', 'wings;', '', 'For', 'is', 'ito', 'the', 'freehearted', 'God', 'for', 'father.', '', '[Illustration:', '0042]', '', '*****', '*****', '', 'Then', 'an', 'inn,', 'and', 'Drinking_.', '', 'And', 'said:', '', 'Would', 'the', 'fragrance', 'air', 'plant', 'light.', '', 'But', 'rob', 'the', 'to', 'quench', 'an', 'act', 'worship,', '', 'And', 'on', 'which', 'of', 'forest', 'that', 'which', 'innocent', 'in', 'man.', '', '*****', '', 'When', 'your', 'heart,', '', '“By', 'too', 'am', 'consumed.', 'For', 'into', 'my', 'mightier', 'hand.', '', 'Your', 'but', 'the', 'heaven.”', '', '*****', '', 'And', 'your', 'teeth,', 'heart,', '', '“Your', 'body,', '', 'And', 'shall', 'blossom', 'heart,', '', 'And', 'breath,', 'And', 'through', 'all', 'seasons.”', '', '*****', '', 'And', 'gather', 'the', 'the', 'winepress,', 'heart,', '', '“I', 'shall', 'be', 'winepress,', '', 'And', 'in', 'eternal', 'vessels.”', '', 'And', 'wine,', 'let', 'song', 'for', 'cup;', '', 'And', 'a', 'remembrance', 'for', 'the', 'winepress.', '', '*****', '*****', '', '', 'Speak', 'to', '_Work_.', '', 'And', 'saying:', '', 'You', 'the', 'earth', 'earth.', '', 'For', 'stranger', 'unto', 'of', 'life’s', 'in', 'majesty', 'the', 'infinite.', '', 'When', 'through', 'whose', 'hours', 'turns', 'music.', '', 'Which', 'and', 'silent,', 'in', 'unison?', '', 'Always', 'a', 'curse', 'misfortune.', '', 'But', 'you', 'fulfil', 'dream,', 'assigned', 'was', 'born,', '', 'And', 'you', 'are', 'life,', '', 'And', 'be', 'intimate', 'secret.', '', '*****', '', 'But', 'an', 'affliction', 'flesh', 'a', 'I', 'answer', 'of', 'your', 'is', 'written.', '', 'You', 'is', 'darkness,', 'echo', 'what', 'weary.', '', 'And', 'darkness', '‘save', 'urge,', '', 'And', 'is', 'knowledge,', '', 'And', 'when', 'there', 'work,', '', 'And', 'is', 'love;', '', 'And', 'bind', 'yourself', 'one', 'another,', 'God.', '', '*****', '', 'And', 'love?', '', 'It', 'threads', 'drawn', 'your', 'beloved', 'cloth.', '', 'It', 'affection,', 'even', 'in', 'that', 'house.', '', 'It', 'and', 'reap', 'if', 'your', 'fruit.', '', 'It', 'fashion', 'with', 'spirit,', '', 'And', 'dead', 'are', 'watching.', '', 'Often', 'if', 'speaking', 'in', 'marble,', 'own', 'soul', 'who', 'ploughs', 'seizes', 'the', 'the', 'likeness', 'who', 'makes', 'feet.”', '', 'But', 'the', 'overwakefulness', 'the', 'wind', 'the', 'giant', 'the', 'blades', 'grass;', '', 'And', 'the', 'voice', 'made', 'sweeter', 'loving.', '', '*****', '', 'Work', 'visible.', '', 'And', 'but', 'only', 'that', 'you', 'at', 'the', 'of', 'those', 'joy.', '', 'For', 'indifference,', 'you', 'but', 'half', 'hunger.', '', 'And', 'the', 'grapes,', 'in', 'the', 'as', 'angels,', 'you', 'muffle', 'the', 'day', 'night.', '', '*****', '*****', '', 'Then', 'of', '_Joy', 'Sorrow_.', '', 'And', 'answered:', '', 'Your', 'unmasked.', '', 'And', 'your', 'laughter', 'filled', 'with', 'tears.', '', 'And', 'be?', '', 'The', 'your', 'being,', 'contain.', '', 'Is', 'the', 'very', 'potter’s', 'oven?', '', 'And', 'your', 'spirit,', 'hollowed', 'with', 'knives?', '', 'When', 'your', 'heart', 'only', 'that', 'is', 'giving', 'joy.', '', 'When', 'in', 'your', 'that', 'in', 'which', 'has', 'delight.', '', '*****', '', 'Some', 'than', 'sorrow,”', 'is', 'the', 'greater.”', '', 'But', 'are', 'inseparable.', '', 'Together', 'sits', 'alone', 'remember', 'that', 'bed.', '', 'Verily', 'scales', 'between', 'joy.', '', 'Only', 'at', 'standstill', 'balanced.', '', 'When', 'to', 'weigh', 'needs', 'must', 'or', 'fall.', '', '*****', '*****', '', 'Then', 'said,', 'Speak', '_Houses_.', '', 'And', 'said:', '', 'Build', 'the', 'wilderness', 'within', 'the', 'walls.', '', 'For', 'in', 'your', 'in', 'you,', 'alone.', '', 'Your', 'body.', '', 'It', 'the', 'stillness', 'not', 'dreamless.', 'dream?', 'and', 'grove', 'or', 'hilltop?', '', 'Would', 'houses', 'into', 'scatter', 'them', 'meadow.', '', 'Would', 'and', 'the', 'you', 'might', 'through', 'vineyards,', 'fragrance', 'of', 'garments.', '', 'But', 'be.', '', 'In', 'gathered', 'you', 'fear', 'shall', 'little', 'longer', 'separate', 'your', 'fields.', '', '*****', '', 'And', 'what', 'have', 'it', 'you', 'doors?', '', 'Have', 'that', 'reveals', 'power?', '', 'Have', 'glimmering', 'arches', 'the', 'mind?', '', 'Have', 'heart', 'from', 'stone', 'to', 'mountain?', '', 'Tell', 'houses?', '', 'Or', 'lust', 'for', 'that', 'enters', 'then', 'becomes', 'master?', '', '*****', '', 'Ay,', 'with', 'hook', 'your', 'larger', 'desires.', '', 'Though', 'heart', 'is', 'iron.', '', 'It', 'by', 'your', 'the', 'flesh.', '', 'It', 'and', 'lays', 'fragile', 'vessels.', '', 'Verily', 'murders', 'the', 'walks', 'grinning', 'funeral.', '', 'But', 'restless', 'in', 'nor', 'tamed.', '', 'Your', 'a', 'mast.', '', 'It', 'that', 'covers', 'that', 'guards', 'eye.', '', 'You', 'you', 'may', 'your', 'heads', 'a', 'ceiling,', 'walls', 'should', 'down.', '', 'You', 'the', 'dead', 'living.', '', 'And', 'and', 'splendour,', 'hold', 'your', 'longing.', '', 'For', 'you', 'abides', 'whose', 'door', 'whose', 'windows', 'silences', 'of', 'night.', '', '*****', '*****', '', 'And', 'of', '_Clothes_.', '', 'And', 'answered:', '', 'Your', 'your', 'beauty,', 'the', 'unbeautiful.', '', 'And', 'the', 'freedom', 'them', 'a', 'chain.', '', 'Would', 'and', 'the', 'less', 'of', 'raiment,', '', 'For', 'the', 'sunlight', 'the', 'wind.', '', 'Some', 'wind', 'who', 'wear.”', '', 'And', 'wind,', '', 'But', 'the', 'softening', 'thread.', '', 'And', 'in', 'the', 'modesty', 'is', 'the', 'unclean.', '', 'And', 'more,', 'what', 'a', 'fouling', 'mind?', '', 'And', 'delights', 'to', 'winds', 'long', 'hair.', '', '*****', '*****', '', 'And', 'of', '_Buying', 'Selling_.', '', 'And', 'said:', '', 'To', 'and', 'you', 'how', 'to', 'hands.', '', 'It', 'the', 'earth', 'and', 'be', 'satisfied.', '', 'Yet', 'and', 'kindly', 'to', 'greed', 'hunger.', '', 'When', 'of', 'the', 'meet', 'the', 'the', 'gatherers', 'spices,--', '', 'Invoke', 'the', 'earth,', 'and', 'sanctify', 'reckoning', 'that', 'And', 'suffer', 'take', 'part', 'would', 'sell', 'labour.', '', 'To', 'say,', '', '“Come', 'with', 'our', 'your', 'net;', '', 'For', 'be', 'bountiful', 'us.”', '', '*****', '', 'And', 'the', 'dancers', 'of', 'their', 'also.', '', 'For', 'and', 'frankincense,', 'bring,', 'though', 'raiment', 'and', 'soul.', '', 'And', 'place,', 'see', 'with', 'empty', 'hands.', '', 'For', 'shall', 'not', 'wind', 'till', 'are', 'satisfied.', '', '*****', '*****', '', 'Then', 'city', 'stood', 'of', '_Crime', 'Punishment_.', '', 'And', 'saying:', '', 'It', 'wandering', 'upon', 'wind,', '', 'That', 'commit', 'a', 'unto', 'yourself.', '', 'And', 'you', 'knock', 'the', 'gate', 'blessed.', '', 'Like', 'god-self;', '', 'It', 'undefiled.', '', 'And', 'the', 'winged.', '', 'Even', 'god-self;', '', 'It', 'nor', 'seeks', 'serpent.', 'But', 'alone', 'in', 'being.', '', 'Much', 'in', 'you', 'man,', '', 'But', 'asleep', 'in', 'own', 'awakening.', '', 'And', 'speak.', '', 'For', 'nor', 'the', 'crime', 'and', 'crime.', '', '*****', '', 'Oftentimes', 'one', 'who', 'were', 'not', 'you', 'and', 'world.', '', 'But', 'the', 'righteous', 'highest', 'which', 'you,', '', 'So', 'fall', 'lower', 'you', 'also.', '', 'And', 'yellow', 'but', 'the', 'whole', 'cannot', 'do', 'you', 'all.', '', 'Like', 'together', 'towards', 'god-self.', '', '[Illustration:', '0064]', '', 'You', 'wayfarers.', '', 'And', 'falls', 'for', 'against', 'the', 'stone.', '', 'Ay,', 'him,', 'who', 'yet', 'removed', 'stone.', '', 'And', 'heavy', 'upon', 'hearts:', '', 'The', 'for', 'his', 'murder,', '', 'And', 'being', 'robbed.', '', 'The', 'the', 'deeds', 'wicked,', '', 'And', 'the', 'doings', 'felon.', '', 'Yea,', 'victim', 'of', 'injured,', '', 'And', 'is', 'the', 'guiltless', 'and', 'unblamed.', '', 'You', 'the', 'unjust', 'wicked;', '', 'For', 'face', 'of', 'and', 'the', 'together.', '', 'And', 'the', 'weaver', 'cloth,', 'and', 'also.', '', '*****', '', 'If', 'judgment', 'the', 'wife,', '', 'Let', 'her', 'husband', 'soul', 'with', 'measurements.', '', 'And', 'offender', 'look', 'offended.', '', 'And', 'the', 'name', 'ax', 'unto', 'its', 'roots;', '', 'And', 'the', 'good', 'the', 'fruitless,', 'in', 'the', 'earth.', '', 'And', 'just,', '', 'What', 'him', 'who', 'a', 'thief', 'spirit?', '', 'What', 'slays', 'in', 'the', 'spirit?', '', 'And', 'action', 'is', 'oppressor,', '', 'Yet', 'outraged?', '', '*****', '', 'And', 'whose', 'remorse', 'their', 'misdeeds?', '', 'Is', 'is', 'administered', 'you', 'would', 'serve?', '', 'Yet', 'the', 'innocent', 'of', 'the', 'guilty.', '', 'Unbidden', 'night,', 'that', 'upon', 'themselves.', 'would', 'understand', 'unless', 'you', 'fullness', 'of', 'light?', '', 'Only', 'erect', 'and', 'standing', 'in', 'his', 'pigmy-self', 'god-self,', 'And', 'temple', 'is', 'in', 'its', 'foundation.', '', '*****', '*****', '', 'Then', 'our', '_Laws_,', 'master?', '', 'And', 'answered:', '', 'You', 'laws,', '', 'Yet', 'them.', '', 'Like', 'who', 'build', 'and', 'then', 'laughter.', '', 'But', 'the', 'ocean', 'shore,', '', 'And', 'ocean', 'laughs', 'you.', '', 'Verily', 'the', 'innocent.', '', 'But', 'not', 'an', 'not', 'sand-towers,', '', 'But', 'law', 'a', 'it', 'in', 'the', 'cripple', 'dancers?', '', 'What', 'and', 'deems', 'forest', 'stray', 'things?', '', 'What', 'shed', 'his', 'and', 'shameless?', '', 'And', 'the', 'wedding-feast,', 'and', 'tired', 'all', 'feasts', 'feasters', 'lawbreakers?', '', '*****', '', 'What', 'that', 'they', 'with', 'their', 'sun?', '', 'They', 'their', 'shadows', 'laws.', '', 'And', 'caster', 'of', 'shadows?', '', 'And', 'the', 'laws', 'their', 'shadows', 'earth?', '', 'But', 'what', 'images', 'hold', 'you?', '', 'You', 'what', 'weather-vane', 'course?', '', 'What', 'you', 'break', 'prison', 'door?', '', 'What', 'dance', 'but', 'iron', 'chains?', '', 'And', 'to', 'judgment', 'garment', 'yet', 'path?', '', '*****', '', 'People', 'the', 'drum,', 'strings', 'of', 'the', 'skylark', 'sing?', '', '*****', '*****', '', 'And', 'of', '_Freedom_.', '', 'And', 'answered:', '', 'At', 'fireside', 'I', 'and', 'worship', 'freedom,', '', 'Even', 'before', 'a', 'slays', 'them.', '', 'Ay,', 'in', 'the', 'seen', 'the', 'freedom', 'as', 'handcuff.', '', 'And', 'you', 'can', 'desire', 'of', 'harness', 'to', 'of', 'freedom', 'fulfilment.', '', 'You', 'yo

In [13]:
# List comprehension way
print(prophet_line)
prophet_flat = [y for x in prophet_line if len(x) > 1 for y in x]
#print(prophet_flat)

[['\ufeffThe'], ['Project'], ['Gutenberg'], ['EBook'], ['of'], ['The'], ['Prophet,'], ['by'], ['Kahlil'], ['Gibran', '', 'This'], ['eBook'], ['is'], ['for'], ['the'], ['use'], ['of'], ['anyone'], ['anywhere'], ['in'], ['the'], ['United'], ['States'], ['and', 'most'], ['other'], ['parts'], ['of'], ['the'], ['world'], ['at'], ['no'], ['cost'], ['and'], ['with'], ['almost'], ['no'], ['restrictions', 'whatsoever.'], [''], ['You'], ['may'], ['copy'], ['it,'], ['give'], ['it'], ['away'], ['or'], ['re-use'], ['it'], ['under'], ['the'], ['terms', 'of'], ['the'], ['Project'], ['Gutenberg'], ['License'], ['included'], ['with'], ['this'], ['eBook'], ['or'], ['online'], ['at', 'www.gutenberg.org.'], [''], ['If'], ['you'], ['are'], ['not'], ['located'], ['in'], ['the'], ['United'], ['States,'], ["you'll", 'have'], ['to'], ['check'], ['the'], ['laws'], ['of'], ['the'], ['country'], ['where'], ['you'], ['are'], ['located'], ['before'], ['using', 'this'], ['ebook.', '', '', '', 'Title:'], ['The'], ['Prophet', '', 'Author:'], ['Kahlil'], ['Gibran', '', 'Release'], ['Date:'], ['January'], ['1,'], ['2019'], ['[EBook'], ['#58585]', 'Last'], ['Updated:'], ['January'], ['3,'], ['2018', '', '', 'Language:'], ['English', '', 'Character'], ['set'], ['encoding:'], ['UTF-8', '', '***'], ['START'], ['OF'], ['THIS'], ['PROJECT'], ['GUTENBERG'], ['EBOOK'], ['THE'], ['PROPHET'], ['***', '', '', '', '', 'Produced'], ['by'], ['David'], ['Widger'], ['from'], ['page'], ['images'], ['generously', 'provided'], ['by'], ['the'], ['Internet'], ['Archive', '', '', "Transcriber's"], ['Note:'], ['Page'], ['numbers,'], ['ie:'], [','], ['are'], ['included'], ['in'], ['this', 'utf-8'], ['text'], ['file.'], ['For'], ['those'], ['wishing'], ['to'], ['use'], ['a'], ['text'], ['file'], ['unencumbered', 'with'], ['page'], ['numbers'], ['open'], ['or'], ['download'], ['the'], ['Latin-1'], ['file'], ['58585-8.txt.', '', '', '', '', '', '', '', 'THE'], ['PROPHET', '', 'By'], ['Kahlil'], ['Gibran', '', 'New'], ['York:'], ['Alfred'], ['A.'], ['Knopf', '', '1923', '', '_The'], ['Twelve'], ['Illustrations'], ['In'], ['This'], ['Volume', 'Are'], ['Reproduced'], ['From'], ['Original'], ['Drawings'], ['By', 'The'], ['Author_', '', '', '“His'], ['power'], ['came'], ['from'], ['some'], ['great'], ['reservoir', 'of'], ['spiritual'], ['life'], ['else'], ['it'], ['could'], ['not'], ['have', 'been'], ['so'], ['universal'], ['and'], ['so'], ['potent,'], ['but'], ['the', 'majesty'], ['and'], ['beauty'], ['of'], ['the'], ['language'], ['with', 'which'], ['he'], ['clothed'], ['it'], ['were'], ['all'], ['his'], ['own?”', '', '--Claude'], ['Bragdon', '', '', 'THE'], ['BOOKS'], ['OF'], ['KAHLIL'], ['GIBRAN', '', 'The'], ['Madman.'], ['1918'], ['Twenty'], ['Drawings.'], ['1919', 'The'], ['Forerunner.'], ['1920'], ['The'], ['Prophet.'], ['1923', 'Sand'], ['and'], ['Foam.'], ['1926'], ['Jesus'], ['the'], ['Son'], ['of', 'Man.'], ['1928'], ['The'], ['Forth'], ['Gods.'], ['1931'], ['The', 'Wanderer.'], ['1932'], ['The'], ['Garden'], ['of'], ['the'], ['Prophet', '1933'], ['Prose'], ['Poems.'], ['1934'], ['Nymphs'], ['of'], ['the', 'Valley.'], ['1948', '', '', '', '', 'CONTENTS', '', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['The'], ['Coming'], ['of'], ['the'], ['Ship.......7', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Love.....................15', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Marriage.................19', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Children.................21', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Giving...................23', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Eating'], ['and'], ['Drinking......27', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Work.....................31', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Joy'], ['and'], ['Sorrow...........33', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Houses...................37', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Clothes..................41', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Buying'], ['and'], ['Selling.......43', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Crime'], ['and'], ['Punishment.....45', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Laws.....................51', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Freedom..................55', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Reason'], ['and'], ['Passion.......57', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Pain.....................60', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Self-Knowledge...........62', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Teaching.................64', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Friendship...............66', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Talking..................68', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Time.....................70', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Good'], ['and'], ['Evil............72', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Prayer...................76', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Pleasure.................79', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Beauty...................83', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Religion.................87', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['On'], ['Death....................90', ''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['The'], ['Farewell................92', '', '', '', '', 'THE'], ['PROPHET', '', '|Almustafa,'], ['the'], ['chosen'], ['and'], ['the', 'beloved,'], ['who'], ['was'], ['a'], ['dawn'], ['unto'], ['his'], ['own', 'day,'], ['had'], ['waited'], ['twelve'], ['years'], ['in'], ['the'], ['city', 'of'], ['Orphalese'], ['for'], ['his'], ['ship'], ['that'], ['was'], ['to', 'return'], ['and'], ['bear'], ['him'], ['back'], ['to'], ['the'], ['isle'], ['of', 'his'], ['birth.', '', 'And'], ['in'], ['the'], ['twelfth'], ['year,'], ['on'], ['the'], ['seventh', 'day'], ['of'], ['Ielool,'], ['the'], ['month'], ['of'], ['reaping,'], ['he', 'climbed'], ['the'], ['hill'], ['without'], ['the'], ['city'], ['walls', 'and'], ['looked'], ['seaward;'], ['and'], ['he'], ['beheld'], ['his', 'ship'], ['coming'], ['with'], ['the'], ['mist.', '', 'Then'], ['the'], ['gates'], ['of'], ['his'], ['heart'], ['were'], ['flung', 'open,'], ['and'], ['his'], ['joy'], ['flew'], ['far'], ['over'], ['the'], ['sea.', 'And'], ['he'], ['closed'], ['his'], ['eyes'], ['and'], ['prayed'], ['in'], ['the', 'silences'], ['of'], ['his'], ['soul.', '', '*****', '', 'But'], ['as'], ['he'], ['descended'], ['the'], ['hill,'], ['a'], ['sadness', 'came'], ['upon'], ['him,'], ['and'], ['he'], ['thought'], ['in'], ['his', 'heart:', '', 'How'], ['shall'], ['I'], ['go'], ['in'], ['peace'], ['and'], ['without', 'sorrow?'], ['Nay,'], ['not'], ['without'], ['a'], ['wound'], ['in'], ['the', 'spirit'], ['shall'], ['I'], ['leave'], ['this'], ['city.'], ['Long', 'were'], ['the'], ['days'], ['of'], ['pain'], ['I'], ['have'], ['spent', 'within'], ['its'], ['walls,'], ['and'], ['long'], ['were'], ['the', 'nights'], ['of'], ['aloneness;'], ['and'], ['who'], ['can'], ['depart', 'from'], ['his'], ['pain'], ['and'], ['his'], ['aloneness'], ['without', 'regret?', '', 'Too'], ['many'], ['fragments'], ['of'], ['the'], ['spirit'], ['have'], ['I', 'scattered'], ['in'], ['these'], ['streets,'], ['and'], ['too'], ['many', 'are'], ['the'], ['children'], ['of'], ['my'], ['longing'], ['that'], ['walk', 'naked'], ['among'], ['these'], ['hills,'], ['and'], ['I'], ['cannot', 'withdraw'], ['from'], ['them'], ['without'], ['a'], ['burden'], ['and', 'an'], ['ache.', '', 'It'], ['is'], ['not'], ['a'], ['garment'], ['I'], ['cast'], ['off'], ['this', 'day,'], ['but'], ['a'], ['skin'], ['that'], ['I'], ['tear'], ['with'], ['my'], ['own', 'hands.', '', 'Nor'], ['is'], ['it'], ['a'], ['thought'], ['I'], ['leave'], ['behind'], ['me,', 'but'], ['a'], ['heart'], ['made'], ['sweet'], ['with'], ['hunger'], ['and', 'with'], ['thirst.', '', '*****', '', 'Yet'], ['I'], ['cannot'], ['tarry'], ['longer.', '', 'The'], ['sea'], ['that'], ['calls'], ['all'], ['things'], ['unto'], ['her', 'calls'], ['me,'], ['and'], ['I'], ['must'], ['embark.', '', 'For'], ['to'], ['stay,'], ['though'], ['the'], ['hours'], ['burn'], ['in', 'the'], ['night,'], ['is'], ['to'], ['freeze'], ['and'], ['crystallize', 'and'], ['be'], ['bound'], ['in'], ['a'], ['mould.', '', 'Fain'], ['would'], ['I'], ['take'], ['with'], ['me'], ['all'], ['that'], ['is', 'here.'], ['But'], ['how'], ['shall'], ['I?', '', 'A'], ['voice'], ['cannot'], ['carry'], ['the'], ['tongue'], ['and', 'the'], ['lips'], ['that'], ['gave'], ['it'], ['wings.'], ['Alone', 'must'], ['it'], ['seek'], ['the'], ['ether.', '', 'And'], ['alone'], ['and'], ['without'], ['his'], ['nest'], ['shall'], ['the', 'eagle'], ['fly'], ['across'], ['the'], ['sun.', '', '*****', '', 'Now'], ['when'], ['he'], ['reached'], ['the'], ['foot'], ['of'], ['the', 'hill,'], ['he'], ['turned'], ['again'], ['towards'], ['the'], ['sea,', 'and'], ['he'], ['saw'], ['his'], ['ship'], ['approaching'], ['the', 'harbour,'], ['and'], ['upon'], ['her'], ['prow'], ['the'], ['mariners,', 'the'], ['men'], ['of'], ['his'], ['own'], ['land.', '', 'And'], ['his'], ['soul'], ['cried'], ['out'], ['to'], ['them,'], ['and'], ['he', 'said:', '', 'Sons'], ['of'], ['my'], ['ancient'], ['mother,'], ['you'], ['riders'], ['of', 'the'], ['tides,', '', 'How'], ['often'], ['have'], ['you'], ['sailed'], ['in'], ['my'], ['dreams.', 'And'], ['now'], ['you'], ['come'], ['in'], ['my'], ['awakening,'], ['which', 'is'], ['my'], ['deeper'], ['dream.', '', 'Ready'], ['am'], ['I'], ['to'], ['go,'], ['and'], ['my'], ['eagerness'], ['with', 'sails'], ['full'], ['set'], ['awaits'], ['the'], ['wind.', '', 'Only'], ['another'], ['breath'], ['will'], ['I'], ['breathe'], ['in', 'this'], ['still'], ['air,'], ['only'], ['another'], ['loving'], ['look', 'cast'], ['backward,', '', 'And'], ['then'], ['I'], ['shall'], ['stand'], ['among'], ['you,'], ['a', 'seafarer'], ['among'], ['seafarers.'], ['And'], ['you,', 'vast'], ['sea,'], ['sleepless'], ['mother,', '', 'Who'], ['alone'], ['are'], ['peace'], ['and'], ['freedom'], ['to'], ['the', 'river'], ['and'], ['the'], ['stream,', '', 'Only'], ['another'], ['winding'], ['will'], ['this'], ['stream', 'make,'], ['only'], ['another'], ['murmur'], ['in'], ['this'], ['glade,', '', 'And'], ['then'], ['shall'], ['I'], ['come'], ['to'], ['you,'], ['a', 'boundless'], ['drop'], ['to'], ['a'], ['boundless'], ['ocean.', '', '*****', '', 'And'], ['as'], ['he'], ['walked'], ['he'], ['saw'], ['from'], ['afar'], ['men', 'and'], ['women'], ['leaving'], ['their'], ['fields'], ['and'], ['their', 'vineyards'], ['and'], ['hastening'], ['towards'], ['the'], ['city', 'gates.', '', 'And'], ['he'], ['heard'], ['their'], ['voices'], ['calling'], ['his', 'name,'], ['and'], ['shouting'], ['from'], ['field'], ['to'], ['field', 'telling'], ['one'], ['another'], ['of'], ['the'], ['coming'], ['of'], ['his', 'ship.', '', 'And'], ['he'], ['said'], ['to'], ['himself:', '', 'Shall'], ['the'], ['day'], ['of'], ['parting'], ['be'], ['the'], ['day'], ['of', 'gathering?', '', 'And'], ['shall'], ['it'], ['be'], ['said'], ['that'], ['my'], ['eve'], ['was'], ['in', 'truth'], ['my'], ['dawn?', '', 'And'], ['what'], ['shall'], ['I'], ['give'], ['unto'], ['him'], ['who'], ['has', 'left'], ['his'], ['plough'], ['in'], ['midfurrow,'], ['or'], ['to', 'him'], ['who'], ['has'], ['stopped'], ['the'], ['wheel'], ['of'], ['his', 'winepress?'], ['Shall'], ['my'], ['heart'], ['become'], ['a', 'tree'], ['heavy-laden'], ['with'], ['fruit'], ['that'], ['I'], ['may', 'gather'], ['and'], ['give'], ['unto'], ['them?', '', 'And'], ['shall'], ['my'], ['desires'], ['flow'], ['like'], ['a', 'fountain'], ['that'], ['I'], ['may'], ['fill'], ['their'], ['cups?', '', 'Am'], ['I'], ['a'], ['harp'], ['that'], ['the'], ['hand'], ['of'], ['the'], ['mighty', 'may'], ['touch'], ['me,'], ['or'], ['a'], ['flute'], ['that'], ['his'], ['breath', 'may'], ['pass'], ['through'], ['me?', '', 'A'], ['seeker'], ['of'], ['silences'], ['am'], ['I,'], ['and'], ['what', 'treasure'], ['have'], ['I'], ['found'], ['in'], ['silences'], ['that'], ['I', 'may'], ['dispense'], ['with'], ['confidence?', '', 'If'], ['this'], ['is'], ['my'], ['day'], ['of'], ['harvest,'], ['in'], ['what', 'fields'], ['have'], ['I'], ['sowed'], ['the'], ['seed,'], ['and'], ['in', 'what'], ['unremembered'], ['seasons?', '', 'If'], ['this'], ['indeed'], ['be'], ['the'], ['hour'], ['in'], ['which'], ['I', 'lift'], ['up'], ['my'], ['lantern,'], ['it'], ['is'], ['not'], ['my'], ['flame', 'that'], ['shall'], ['burn'], ['therein.', '', 'Empty'], ['and'], ['dark'], ['shall'], ['I'], ['raise'], ['my'], ['lantern,', '', 'And'], ['the'], ['guardian'], ['of'], ['the'], ['night'], ['shall'], ['fill', 'it'], ['with'], ['oil'], ['and'], ['he'], ['shall'], ['light'], ['it'], ['also.', '', '*****', '', 'These'], ['things'], ['he'], ['said'], ['in'], ['words.'], ['But'], ['much', 'in'], ['his'], ['heart'], ['remained'], ['unsaid.'], ['For'], ['he', 'himself'], ['could'], ['not'], ['speak'], ['his'], ['deeper', 'secret.', '', '*****', '', '[Illustration:'], ['0020]', '', 'And'], ['when'], ['he'], ['entered'], ['into'], ['the'], ['city'], ['all', 'the'], ['people'], ['came'], ['to'], ['meet'], ['him,'], ['and'], ['they', 'were'], ['crying'], ['out'], ['to'], ['him'], ['as'], ['with'], ['one', 'voice.', '', 'And'], ['the'], ['elders'], ['of'], ['the'], ['city'], ['stood'], ['forth', 'and'], ['said:', '', 'Go'], ['not'], ['yet'], ['away'], ['from'], ['us.', '', 'A'], ['noontide'], ['have'], ['you'], ['been'], ['in'], ['our', 'twilight,'], ['and'], ['your'], ['youth'], ['has'], ['given'], ['us', 'dreams'], ['to'], ['dream.', '', 'No'], ['stranger'], ['are'], ['you'], ['among'], ['us,'], ['nor', 'a'], ['guest,'], ['but'], ['our'], ['son'], ['and'], ['our'], ['dearly', 'beloved.', '', 'Suffer'], ['not'], ['yet'], ['our'], ['eyes'], ['to'], ['hunger'], ['for', 'your'], ['face.', '', '*****', '', 'And'], ['the'], ['priests'], ['and'], ['the'], ['priestesses'], ['said', 'unto'], ['him:', '', 'Let'], ['not'], ['the'], ['waves'], ['of'], ['the'], ['sea'], ['separate'], ['us', 'now,'], ['and'], ['the'], ['years'], ['you'], ['have'], ['spent'], ['in'], ['our', 'midst'], ['become'], ['a'], ['memory.', '', 'You'], ['have'], ['walked'], ['among'], ['us'], ['a'], ['spirit,', 'and'], ['your'], ['shadow'], ['has'], ['been'], ['a'], ['light', 'upon'], ['our'], ['faces.', '', 'Much'], ['have'], ['we'], ['loved'], ['you.'], ['But'], ['speechless', 'was'], ['our'], ['love,'], ['and'], ['with'], ['veils'], ['has'], ['it'], ['been', 'veiled.', '', 'Yet'], ['now'], ['it'], ['cries'], ['aloud'], ['unto'], ['you,'], ['and', 'would'], ['stand'], ['revealed'], ['before'], ['you.', '', 'And'], ['ever'], ['has'], ['it'], ['been'], ['that'], ['love'], ['knows', 'not'], ['its'], ['own'], ['depth'], ['until'], ['the'], ['hour'], ['of', 'separation.', '', '*****', '', 'And'], ['others'], ['came'], ['also'], ['and'], ['entreated'], ['him.', 'But'], ['he'], ['answered'], ['them'], ['not.'], ['He'], ['only'], ['bent', 'his'], ['head;'], ['and'], ['those'], ['who'], ['stood'], ['near'], ['saw', 'his'], ['tears'], ['falling'], ['upon'], ['his'], ['breast.', '', 'And'], ['he'], ['and'], ['the'], ['people'], ['proceeded'], ['towards', 'the'], ['great'], ['square'], ['before'], ['the'], ['temple.', '', 'And'], ['there'], ['came'], ['out'], ['of'], ['the'], ['sanctuary'], ['a', 'woman'], ['whose'], ['name'], ['was'], ['Almitra.'], ['And'], ['she', 'was'], ['a'], ['seeress.', '', 'And'], ['he'], ['looked'], ['upon'], ['her'], ['with'], ['exceeding', 'tenderness,'], ['for'], ['it'], ['was'], ['she'], ['who'], ['had'], ['first', 'sought'], ['and'], ['believed'], ['in'], ['him'], ['when'], ['he'], ['had', 'been'], ['but'], ['a'], ['day'], ['in'], ['their'], ['city.'], ['And', 'she'], ['hailed'], ['him,'], ['saying:', '', 'Prophet'], ['of'], ['God,'], ['in'], ['quest'], ['of'], ['the', 'uttermost,'], ['long'], ['have'], ['you'], ['searched'], ['the', 'distances'], ['for'], ['your'], ['ship.', '', 'And'], ['now'], ['your'], ['ship'], ['has'], ['come,'], ['and'], ['you'], ['must', 'needs'], ['go.', '', 'Deep'], ['is'], ['your'], ['longing'], ['for'], ['the'], ['land'], ['of', 'your'], ['memories'], ['and'], ['the'], ['dwelling'], ['place', 'of'], ['your'], ['greater'], ['desires;'], ['and'], ['our'], ['love', 'would'], ['not'], ['bind'], ['you'], ['nor'], ['our'], ['needs'], ['hold', 'you.', '', 'Yet'], ['this'], ['we'], ['ask'], ['ere'], ['you'], ['leave'], ['us,'], ['that', 'you'], ['speak'], ['to'], ['us'], ['and'], ['give'], ['us'], ['of'], ['your', 'truth.', '', 'And'], ['we'], ['will'], ['give'], ['it'], ['unto'], ['our'], ['children,', 'and'], ['they'], ['unto'], ['their'], ['children,'], ['and'], ['it', 'shall'], ['not'], ['perish.', '', 'In'], ['your'], ['aloneness'], ['you'], ['have'], ['watched'], ['with', 'our'], ['days,'], ['and'], ['in'], ['your'], ['wakefulness'], ['you', 'have'], ['listened'], ['to'], ['the'], ['weeping'], ['and'], ['the', 'laughter'], ['of'], ['our'], ['sleep.', '', 'Now'], ['therefore'], ['disclose'], ['us'], ['to'], ['ourselves,', 'and'], ['tell'], ['us'], ['all'], ['that'], ['has'], ['been'], ['shown', 'you'], ['of'], ['that'], ['which'], ['is'], ['between'], ['birth'], ['and', 'death.', '', '*****', '', 'And'], ['he'], ['answered,', '', 'People'], ['of'], ['Orphalese,'], ['of'], ['what'], ['can'], ['I', 'speak'], ['save'], ['of'], ['that'], ['which'], ['is'], ['even'], ['now', 'moving'], ['within'], ['your'], ['souls?', '', '*****'], ['*****', '', 'Then'], ['said'], ['Almitra,'], ['Speak'], ['to'], ['us'], ['of', '_Love_.', '', 'And'], ['he'], ['raised'], ['his'], ['head'], ['and'], ['looked'], ['upon', 'the'], ['people,'], ['and'], ['there'], ['fell'], ['a'], ['stillness', 'upon'], ['them.'], ['And'], ['with'], ['a'], ['great'], ['voice'], ['he', 'said:', '', 'When'], ['love'], ['beckons'], ['to'], ['you,'], ['follow'], ['him,', '', 'Though'], ['his'], ['ways'], ['are'], ['hard'], ['and'], ['steep.', '', 'And'], ['when'], ['his'], ['wings'], ['enfold'], ['you'], ['yield'], ['to', 'him,', '', 'Though'], ['the'], ['sword'], ['hidden'], ['among'], ['his', 'pinions'], ['may'], ['wound'], ['you.', '', 'And'], ['when'], ['he'], ['speaks'], ['to'], ['you'], ['believe'], ['in', 'him,', '', 'Though'], ['his'], ['voice'], ['may'], ['shatter'], ['your'], ['dreams', 'as'], ['the'], ['north'], ['wind'], ['lays'], ['waste'], ['the'], ['garden.', '', 'For'], ['even'], ['as'], ['love'], ['crowns'], ['you'], ['so'], ['shall', 'he'], ['crucify'], ['you.'], ['Even'], ['as'], ['he'], ['is'], ['for'], ['your', 'growth'], ['so'], ['is'], ['he'], ['for'], ['your'], ['pruning.', '', 'Even'], ['as'], ['he'], ['ascends'], ['to'], ['your'], ['height'], ['and', 'caresses'], ['your'], ['tenderest'], ['branches', 'that'], ['quiver'], ['in'], ['the'], ['sun,', '', 'So'], ['shall'], ['he'], ['descend'], ['to'], ['your'], ['roots'], ['and', 'shake'], ['them'], ['in'], ['their'], ['clinging'], ['to'], ['the', 'earth.', '', '*****', '', 'Like'], ['sheaves'], ['of'], ['corn'], ['he'], ['gathers'], ['you'], ['unto', 'himself.', '', 'He'], ['threshes'], ['you'], ['to'], ['make'], ['you'], ['naked.', '', 'He'], ['sifts'], ['you'], ['to'], ['free'], ['you'], ['from'], ['your', 'husks.', '', 'He'], ['grinds'], ['you'], ['to'], ['whiteness.', '', 'He'], ['kn

# Challenge 2 - Filtering

When printing out a few words from the book, we see that there are words that we may not want to keep if we choose to analyze the corpus of text. Below is a list of words that we would like to get rid of. Create a function that will return false if it contains a word from the list of words specified and true otherwise.

In [14]:

def word_filter(x):
    '''
    Input: A string
    Output: True if the word is not in the specified list 
    and False if the word is in the list.
        
    Example:
    word list = ['and', 'the']
    Input: 'and'
    Output: False
    
    Input: 'John'
    Output: True
    '''
    words_eq = []

    word_list = ['and', 'the', 'a', 'an']
    for y in word_list:
        x = x.lower()
        
        if x == y:
            words_eq.append(y)
        else:
            pass
    #print(len(words_eq))
    if len(words_eq) == 0:
        return True
    else:
        words_eq.clear()
        return False
    
    
    # your code here

In [15]:
word_filter("lolo")

True

Use the `filter()` function to filter out the words speficied in the `word_filter()` function. Store the filtered list in the variable `prophet_filter`.

In [16]:
print(prophet_flat)
prophet_filter = list(filter(word_filter,prophet_flat))
print(prophet_filter[0:100])

['Gibran', '', 'This', 'and', 'most', 'restrictions', 'whatsoever.', 'terms', 'of', 'at', 'www.gutenberg.org.', "you'll", 'have', 'using', 'this', 'ebook.', '', '', '', 'Title:', 'Prophet', '', 'Author:', 'Gibran', '', 'Release', '#58585]', 'Last', '2018', '', '', 'Language:', 'English', '', 'Character', 'UTF-8', '', '***', '***', '', '', '', '', 'Produced', 'generously', 'provided', 'Archive', '', '', "Transcriber's", 'this', 'utf-8', 'unencumbered', 'with', '58585-8.txt.', '', '', '', '', '', '', '', 'THE', 'PROPHET', '', 'By', 'Gibran', '', 'New', 'Knopf', '', '1923', '', '_The', 'Volume', 'Are', 'By', 'The', 'Author_', '', '', '“His', 'reservoir', 'of', 'have', 'been', 'the', 'majesty', 'with', 'which', 'own?”', '', '--Claude', 'Bragdon', '', '', 'THE', 'GIBRAN', '', 'The', '1919', 'The', '1923', 'Sand', 'of', 'Man.', 'The', 'Wanderer.', 'Prophet', '1933', 'the', 'Valley.', '1948', '', '', '', '', 'CONTENTS', '', '', 'Ship.......7', '', 'Love.....................15', '', 'Marriage.................19', '', 'Children.................21', '', 'Giving...................23', '', 'Drinking......27', '', 'Work.....................31', '', 'Sorrow...........33', '', 'Houses...................37', '', 'Clothes..................41', '', 'Selling.......43', '', 'Punishment.....45', '', 'Laws.....................51', '', 'Freedom..................55', '', 'Passion.......57', '', 'Pain.....................60', '', 'Self-Knowledge...........62', '', 'Teaching.................64', '', 'Friendship...............66', '', 'Talking..................68', '', 'Time.....................70', '', 'Evil............72', '', 'Prayer...................76', '', 'Pleasure.................79', '', 'Beauty...................83', '', 'Religion.................87', '', 'Death....................90', '', 'Farewell................92', '', '', '', '', 'THE', 'PROPHET', '', '|Almustafa,', 'the', 'beloved,', 'own', 'day,', 'city', 'of', 'to', 'return', 'of', 'his', 'birth.', '', 'And', 'seventh', 'day', 'he', 'climbed', 'walls', 'and', 'his', 'ship', 'mist.', '', 'Then', 'flung', 'open,', 'sea.', 'And', 'the', 'silences', 'soul.', '', '*****', '', 'But', 'sadness', 'came', 'his', 'heart:', '', 'How', 'without', 'sorrow?', 'the', 'spirit', 'Long', 'were', 'spent', 'within', 'the', 'nights', 'depart', 'from', 'without', 'regret?', '', 'Too', 'I', 'scattered', 'many', 'are', 'walk', 'naked', 'cannot', 'withdraw', 'and', 'an', 'ache.', '', 'It', 'this', 'day,', 'own', 'hands.', '', 'Nor', 'me,', 'but', 'and', 'with', 'thirst.', '', '*****', '', 'Yet', 'longer.', '', 'The', 'her', 'calls', 'embark.', '', 'For', 'in', 'the', 'crystallize', 'and', 'mould.', '', 'Fain', 'is', 'here.', 'I?', '', 'A', 'and', 'the', 'Alone', 'must', 'ether.', '', 'And', 'the', 'eagle', 'sun.', '', '*****', '', 'Now', 'the', 'hill,', 'sea,', 'and', 'the', 'harbour,', 'mariners,', 'the', 'land.', '', 'And', 'he', 'said:', '', 'Sons', 'of', 'the', 'tides,', '', 'How', 'dreams.', 'And', 'which', 'is', 'dream.', '', 'Ready', 'with', 'sails', 'wind.', '', 'Only', 'in', 'this', 'look', 'cast', 'backward,', '', 'And', 'a', 'seafarer', 'you,', 'vast', 'mother,', '', 'Who', 'the', 'river', 'stream,', '', 'Only', 'stream', 'make,', 'glade,', '', 'And', 'a', 'boundless', 'ocean.', '', '*****', '', 'And', 'men', 'and', 'their', 'vineyards', 'city', 'gates.', '', 'And', 'his', 'name,', 'field', 'telling', 'his', 'ship.', '', 'And', 'himself:', '', 'Shall', 'of', 'gathering?', '', 'And', 'in', 'truth', 'dawn?', '', 'And', 'has', 'left', 'to', 'him', 'his', 'winepress?', 'a', 'tree', 'may', 'gather', 'them?', '', 'And', 'a', 'fountain', 'cups?', '', 'Am', 'mighty', 'may', 'breath', 'may', 'me?', '', 'A', 'what', 'treasure', 'I', 'may', 'confidence?', '', 'If', 'what', 'fields', 'in', 'what', 'seasons?', '', 'If', 'I', 'lift', 'flame', 'that', 'therein.', '', 'Empty', 'lantern,', '', 'And', 'fill', 'it', 'also.', '', '*****', '', 'These', 'much', 'in', 'he', 'himself', 'deeper', 'secret.', '', '*****', '', '[Illustration:', '0020]', '', 'And', 'all', 'the', 'they', 'were', 'one', 'voice.', '', 'And', 'forth', 'and', 'said:', '', 'Go', 'us.', '', 'A', 'our', 'twilight,', 'us', 'dreams', 'dream.', '', 'No', 'nor', 'a', 'dearly', 'beloved.', '', 'Suffer', 'for', 'your', 'face.', '', '*****', '', 'And', 'said', 'unto', 'him:', '', 'Let', 'us', 'now,', 'our', 'midst', 'memory.', '', 'You', 'spirit,', 'and', 'light', 'upon', 'faces.', '', 'Much', 'speechless', 'was', 'been', 'veiled.', '', 'Yet', 'and', 'would', 'you.', '', 'And', 'knows', 'not', 'of', 'separation.', '', '*****', '', 'And', 'him.', 'But', 'bent', 'his', 'saw', 'his', 'breast.', '', 'And', 'towards', 'the', 'temple.', '', 'And', 'a', 'woman', 'she', 'was', 'seeress.', '', 'And', 'exceeding', 'tenderness,', 'first', 'sought', 'had', 'been', 'And', 'she', 'saying:', '', 'Prophet', 'the', 'uttermost,', 'the', 'distances', 'ship.', '', 'And', 'must', 'needs', 'go.', '', 'Deep', 'of', 'your', 'place', 'of', 'love', 'would', 'hold', 'you.', '', 'Yet', 'that', 'you', 'your', 'truth.', '', 'And', 'children,', 'and', 'it', 'shall', 'perish.', '', 'In', 'with', 'our', 'you', 'have', 'the', 'laughter', 'sleep.', '', 'Now', 'ourselves,', 'and', 'shown', 'you', 'and', 'death.', '', '*****', '', 'And', 'answered,', '', 'People', 'I', 'speak', 'now', 'moving', 'souls?', '', '*****', '*****', '', 'Then', 'of', '_Love_.', '', 'And', 'upon', 'the', 'stillness', 'upon', 'he', 'said:', '', 'When', 'him,', '', 'Though', 'steep.', '', 'And', 'to', 'him,', '', 'Though', 'his', 'pinions', 'you.', '', 'And', 'in', 'him,', '', 'Though', 'dreams', 'as', 'garden.', '', 'For', 'shall', 'he', 'your', 'growth', 'pruning.', '', 'Even', 'and', 'caresses', 'branches', 'that', 'sun,', '', 'So', 'and', 'shake', 'the', 'earth.', '', '*****', '', 'Like', 'unto', 'himself.', '', 'He', 'naked.', '', 'He', 'your', 'husks.', '', 'He', 'whiteness.', '', 'He', 'pliant;', '', 'And', 'sacred', 'fire,', 'bread', 'for', 'feast.', '', '*****', '', 'All', 'you', 'that', 'your', 'heart,', 'a', 'fragment', 'heart.', '', 'But', 'only', 'love’s', 'pleasure,', '', 'Then', 'you', 'cover', 'of', 'love’s', 'threshing-floor,', '', 'Into', 'you', 'shall', 'your', 'laughter,', 'your', 'tears.', '', '*****', '', 'Love', 'takes', 'naught', 'itself.', '', 'Love', 'be', 'possessed;', '', 'For', 'love.', '', 'When', '“God', 'is', 'in', 'the', 'God.”', '', 'And', 'course', 'of', 'you', 'worthy,', 'course.', '', 'Love', 'fulfil', 'itself.', '', 'But', 'have', 'desires,', 'desires:', '', 'To', 'that', 'sings', 'To', 'know', 'tenderness.', '', 'To', 'understanding', 'of', 'love;', '', 'And', 'joyfully.', '', 'To', 'and', 'give', 'loving;', '', 'To', 'meditate', 'love’s', 'ecstacy;', '', 'To', 'with', 'gratitude;', '', 'And', 'for', 'the', 'of', 'praise', 'lips.', '', '[Illustration:', '0029]', '', '*****', '*****', '', 'Then', 'said,', 'And', 'master?', '', 'And', 'saying:', '', 'You', 'you', 'shall', 'forevermore.', '', 'You', 'white', 'wings', 'days.', '', 'Aye,', 'the', 'silent', 'God.', '', 'But', 'your', 'togetherness,', '', 'And', 'dance', 'between', 'you.', '', '*****', '', 'Love', 'of', 'love:', '', 'Let', 'between', 'the', 'souls.', '', 'Fill', 'from', 'one', 'cup.', '', 'Give', 'eat', 'not', 'and', 'dance', 'let', 'each', 'alone,', '', 'Even', 'alone', 'though', 'music.', '', '*****', '', 'Give', 'each', 'other’s', 'keeping.', '', 'For', 'contain', 'your', 'hearts.', '', 'And', 'near', 'together:', '', 'For', 'stand', 'apart,', '', 'And', 'grow', 'not', 'shadow.', '', '[Illustration:', '0032]', '', '*****', '*****', '', 'And', 'babe', 'against', 'of', '_Children_.', '', 'And', 'said:', '', 'Your', 'children.', '', 'They', 'of', 'Life’s', 'itself.', '', 'They', 'you,', '', 'And', 'they', 'belong', 'you.', '', '*****', '', 'You', 'your', 'thoughts,', '', 'For', 'thoughts.', '', 'You', 'their', 'souls,', '', 'For', 'of', 'tomorrow,', 'not', 'even', 'dreams.', '', 'You', 'seek', 'not', 'For', 'life', 'with', 'yesterday.', '', 'You', 'your', 'children', 'sent', 'forth.', '', 'The', 'path', 'of', 'with', 'His', 'swift', 'and', 'far.', '', 'Let', 'be', 'for', 'gladness;', '', 'For', 'that', 'flies,', 'is', 'stable.', '', '*****', '*****', '', 'Then', 'of', '_Giving_.', '', 'And', 'answered:', '', 'You', 'of', 'your', 'possessions.', '', 'It', 'you', 'truly', 'give.', '', 'For', 'things', 'you', 'need', 'them', 'tomorrow?', '', 'And', 'bring', 'to', 'bones', 'in', 'the', 'pilgrims', 'city?', '', 'And', 'need', 'itself?', '', 'Is', 'is', 'full,', 'unquenchable?', '', 'There', 'the', 'much', 'give', 'it', 'hidden', 'desire', 'unwholesome.', '', 'And', 'and', 'give', 'all.', '', 'These', 'and', 'the', 'is', 'never', 'empty.', '', 'There', 'and', 'that', 'reward.', '', 'And', 'pain,', 'and', 'baptism.', '', 'And', 'know', 'not', 'seek', 'joy,', 'of', 'virtue;', '', 'They', 'myrtle', 'breathes', 'space.', '', 'Through', 'God', 'speaks,', 'He', 'smiles', 'earth.', '', '[Illustration:', '0039]', '', 'It', 'it', 'is', 'through', 'understanding;', '', 'And', 'for', 'one', 'greater', 'than', 'giving.', '', 'And', 'withhold?', '', 'All', 'given;', '', 'Therefore', 'season', 'of', 'your', 'inheritors’.', '', 'You', 'only', 'to', 'deserving.”', '', 'The', 'so,', 'nor', 'pasture.', '', 'They', 'to', 'withhold', 'perish.', '', 'Surely', 'his', 'days', 'all', 'else', 'you.', '', 'And', 'from', 'the', 'his', 'cup', 'stream.', '', 'And', 'be,', 'than', 'courage', 'and', 'of', 'receiving?', '', 'And', 'rend', 'their', 'pride,', 'that', 'and', 'their', 'unabashed?', '', 'See', 'to', 'be', 'giving.', '', 'For', 'unto', 'life--while', 'a', 'giver,', 'witness.', '', 'And', 'are', 'all', 'of', 'gratitude,', 'upon', 'yourself', 'gives.', '', 'Rather', 'on', 'his', 'wings;', '', 'For', 'is', 'ito', 'the', 'freehearted', 'God', 'for', 'father.', '', '[Illustration:', '0042]', '', '*****', '*****', '', 'Then', 'an', 'inn,', 'and', 'Drinking_.', '', 'And', 'said:', '', 'Would', 'the', 'fragrance', 'air', 'plant', 'light.', '', 'But', 'rob', 'the', 'to', 'quench', 'an', 'act', 'worship,', '', 'And', 'on', 'which', 'of', 'forest', 'that', 'which', 'innocent', 'in', 'man.', '', '*****', '', 'When', 'your', 'heart,', '', '“By', 'too', 'am', 'consumed.', 'For', 'into', 'my', 'mightier', 'hand.', '', 'Your', 'but', 'the', 'heaven.”', '', '*****', '', 'And', 'your', 'teeth,', 'heart,', '', '“Your', 'body,', '', 'And', 'shall', 'blossom', 'heart,', '', 'And', 'breath,', 'And', 'through', 'all', 'seasons.”', '', '*****', '', 'And', 'gather', 'the', 'the', 'winepress,', 'heart,', '', '“I', 'shall', 'be', 'winepress,', '', 'And', 'in', 'eternal', 'vessels.”', '', 'And', 'wine,', 'let', 'song', 'for', 'cup;', '', 'And', 'a', 'remembrance', 'for', 'the', 'winepress.', '', '*****', '*****', '', '', 'Speak', 'to', '_Work_.', '', 'And', 'saying:', '', 'You', 'the', 'earth', 'earth.', '', 'For', 'stranger', 'unto', 'of', 'life’s', 'in', 'majesty', 'the', 'infinite.', '', 'When', 'through', 'whose', 'hours', 'turns', 'music.', '', 'Which', 'and', 'silent,', 'in', 'unison?', '', 'Always', 'a', 'curse', 'misfortune.', '', 'But', 'you', 'fulfil', 'dream,', 'assigned', 'was', 'born,', '', 'And', 'you', 'are', 'life,', '', 'And', 'be', 'intimate', 'secret.', '', '*****', '', 'But', 'an', 'affliction', 'flesh', 'a', 'I', 'answer', 'of', 'your', 'is', 'written.', '', 'You', 'is', 'darkness,', 'echo', 'what', 'weary.', '', 'And', 'darkness', '‘save', 'urge,', '', 'And', 'is', 'knowledge,', '', 'And', 'when', 'there', 'work,', '', 'And', 'is', 'love;', '', 'And', 'bind', 'yourself', 'one', 'another,', 'God.', '', '*****', '', 'And', 'love?', '', 'It', 'threads', 'drawn', 'your', 'beloved', 'cloth.', '', 'It', 'affection,', 'even', 'in', 'that', 'house.', '', 'It', 'and', 'reap', 'if', 'your', 'fruit.', '', 'It', 'fashion', 'with', 'spirit,', '', 'And', 'dead', 'are', 'watching.', '', 'Often', 'if', 'speaking', 'in', 'marble,', 'own', 'soul', 'who', 'ploughs', 'seizes', 'the', 'the', 'likeness', 'who', 'makes', 'feet.”', '', 'But', 'the', 'overwakefulness', 'the', 'wind', 'the', 'giant', 'the', 'blades', 'grass;', '', 'And', 'the', 'voice', 'made', 'sweeter', 'loving.', '', '*****', '', 'Work', 'visible.', '', 'And', 'but', 'only', 'that', 'you', 'at', 'the', 'of', 'those', 'joy.', '', 'For', 'indifference,', 'you', 'but', 'half', 'hunger.', '', 'And', 'the', 'grapes,', 'in', 'the', 'as', 'angels,', 'you', 'muffle', 'the', 'day', 'night.', '', '*****', '*****', '', 'Then', 'of', '_Joy', 'Sorrow_.', '', 'And', 'answered:', '', 'Your', 'unmasked.', '', 'And', 'your', 'laughter', 'filled', 'with', 'tears.', '', 'And', 'be?', '', 'The', 'your', 'being,', 'contain.', '', 'Is', 'the', 'very', 'potter’s', 'oven?', '', 'And', 'your', 'spirit,', 'hollowed', 'with', 'knives?', '', 'When', 'your', 'heart', 'only', 'that', 'is', 'giving', 'joy.', '', 'When', 'in', 'your', 'that', 'in', 'which', 'has', 'delight.', '', '*****', '', 'Some', 'than', 'sorrow,”', 'is', 'the', 'greater.”', '', 'But', 'are', 'inseparable.', '', 'Together', 'sits', 'alone', 'remember', 'that', 'bed.', '', 'Verily', 'scales', 'between', 'joy.', '', 'Only', 'at', 'standstill', 'balanced.', '', 'When', 'to', 'weigh', 'needs', 'must', 'or', 'fall.', '', '*****', '*****', '', 'Then', 'said,', 'Speak', '_Houses_.', '', 'And', 'said:', '', 'Build', 'the', 'wilderness', 'within', 'the', 'walls.', '', 'For', 'in', 'your', 'in', 'you,', 'alone.', '', 'Your', 'body.', '', 'It', 'the', 'stillness', 'not', 'dreamless.', 'dream?', 'and', 'grove', 'or', 'hilltop?', '', 'Would', 'houses', 'into', 'scatter', 'them', 'meadow.', '', 'Would', 'and', 'the', 'you', 'might', 'through', 'vineyards,', 'fragrance', 'of', 'garments.', '', 'But', 'be.', '', 'In', 'gathered', 'you', 'fear', 'shall', 'little', 'longer', 'separate', 'your', 'fields.', '', '*****', '', 'And', 'what', 'have', 'it', 'you', 'doors?', '', 'Have', 'that', 'reveals', 'power?', '', 'Have', 'glimmering', 'arches', 'the', 'mind?', '', 'Have', 'heart', 'from', 'stone', 'to', 'mountain?', '', 'Tell', 'houses?', '', 'Or', 'lust', 'for', 'that', 'enters', 'then', 'becomes', 'master?', '', '*****', '', 'Ay,', 'with', 'hook', 'your', 'larger', 'desires.', '', 'Though', 'heart', 'is', 'iron.', '', 'It', 'by', 'your', 'the', 'flesh.', '', 'It', 'and', 'lays', 'fragile', 'vessels.', '', 'Verily', 'murders', 'the', 'walks', 'grinning', 'funeral.', '', 'But', 'restless', 'in', 'nor', 'tamed.', '', 'Your', 'a', 'mast.', '', 'It', 'that', 'covers', 'that', 'guards', 'eye.', '', 'You', 'you', 'may', 'your', 'heads', 'a', 'ceiling,', 'walls', 'should', 'down.', '', 'You', 'the', 'dead', 'living.', '', 'And', 'and', 'splendour,', 'hold', 'your', 'longing.', '', 'For', 'you', 'abides', 'whose', 'door', 'whose', 'windows', 'silences', 'of', 'night.', '', '*****', '*****', '', 'And', 'of', '_Clothes_.', '', 'And', 'answered:', '', 'Your', 'your', 'beauty,', 'the', 'unbeautiful.', '', 'And', 'the', 'freedom', 'them', 'a', 'chain.', '', 'Would', 'and', 'the', 'less', 'of', 'raiment,', '', 'For', 'the', 'sunlight', 'the', 'wind.', '', 'Some', 'wind', 'who', 'wear.”', '', 'And', 'wind,', '', 'But', 'the', 'softening', 'thread.', '', 'And', 'in', 'the', 'modesty', 'is', 'the', 'unclean.', '', 'And', 'more,', 'what', 'a', 'fouling', 'mind?', '', 'And', 'delights', 'to', 'winds', 'long', 'hair.', '', '*****', '*****', '', 'And', 'of', '_Buying', 'Selling_.', '', 'And', 'said:', '', 'To', 'and', 'you', 'how', 'to', 'hands.', '', 'It', 'the', 'earth', 'and', 'be', 'satisfied.', '', 'Yet', 'and', 'kindly', 'to', 'greed', 'hunger.', '', 'When', 'of', 'the', 'meet', 'the', 'the', 'gatherers', 'spices,--', '', 'Invoke', 'the', 'earth,', 'and', 'sanctify', 'reckoning', 'that', 'And', 'suffer', 'take', 'part', 'would', 'sell', 'labour.', '', 'To', 'say,', '', '“Come', 'with', 'our', 'your', 'net;', '', 'For', 'be', 'bountiful', 'us.”', '', '*****', '', 'And', 'the', 'dancers', 'of', 'their', 'also.', '', 'For', 'and', 'frankincense,', 'bring,', 'though', 'raiment', 'and', 'soul.', '', 'And', 'place,', 'see', 'with', 'empty', 'hands.', '', 'For', 'shall', 'not', 'wind', 'till', 'are', 'satisfied.', '', '*****', '*****', '', 'Then', 'city', 'stood', 'of', '_Crime', 'Punishment_.', '', 'And', 'saying:', '', 'It', 'wandering', 'upon', 'wind,', '', 'That', 'commit', 'a', 'unto', 'yourself.', '', 'And', 'you', 'knock', 'the', 'gate', 'blessed.', '', 'Like', 'god-self;', '', 'It', 'undefiled.', '', 'And', 'the', 'winged.', '', 'Even', 'god-self;', '', 'It', 'nor', 'seeks', 'serpent.', 'But', 'alone', 'in', 'being.', '', 'Much', 'in', 'you', 'man,', '', 'But', 'asleep', 'in', 'own', 'awakening.', '', 'And', 'speak.', '', 'For', 'nor', 'the', 'crime', 'and', 'crime.', '', '*****', '', 'Oftentimes', 'one', 'who', 'were', 'not', 'you', 'and', 'world.', '', 'But', 'the', 'righteous', 'highest', 'which', 'you,', '', 'So', 'fall', 'lower', 'you', 'also.', '', 'And', 'yellow', 'but', 'the', 'whole', 'cannot', 'do', 'you', 'all.', '', 'Like', 'together', 'towards', 'god-self.', '', '[Illustration:', '0064]', '', 'You', 'wayfarers.', '', 'And', 'falls', 'for', 'against', 'the', 'stone.', '', 'Ay,', 'him,', 'who', 'yet', 'removed', 'stone.', '', 'And', 'heavy', 'upon', 'hearts:', '', 'The', 'for', 'his', 'murder,', '', 'And', 'being', 'robbed.', '', 'The', 'the', 'deeds', 'wicked,', '', 'And', 'the', 'doings', 'felon.', '', 'Yea,', 'victim', 'of', 'injured,', '', 'And', 'is', 'the', 'guiltless', 'and', 'unblamed.', '', 'You', 'the', 'unjust', 'wicked;', '', 'For', 'face', 'of', 'and', 'the', 'together.', '', 'And', 'the', 'weaver', 'cloth,', 'and', 'also.', '', '*****', '', 'If', 'judgment', 'the', 'wife,', '', 'Let', 'her', 'husband', 'soul', 'with', 'measurements.', '', 'And', 'offender', 'look', 'offended.', '', 'And', 'the', 'name', 'ax', 'unto', 'its', 'roots;', '', 'And', 'the', 'good', 'the', 'fruitless,', 'in', 'the', 'earth.', '', 'And', 'just,', '', 'What', 'him', 'who', 'a', 'thief', 'spirit?', '', 'What', 'slays', 'in', 'the', 'spirit?', '', 'And', 'action', 'is', 'oppressor,', '', 'Yet', 'outraged?', '', '*****', '', 'And', 'whose', 'remorse', 'their', 'misdeeds?', '', 'Is', 'is', 'administered', 'you', 'would', 'serve?', '', 'Yet', 'the', 'innocent', 'of', 'the', 'guilty.', '', 'Unbidden', 'night,', 'that', 'upon', 'themselves.', 'would', 'understand', 'unless', 'you', 'fullness', 'of', 'light?', '', 'Only', 'erect', 'and', 'standing', 'in', 'his', 'pigmy-self', 'god-self,', 'And', 'temple', 'is', 'in', 'its', 'foundation.', '', '*****', '*****', '', 'Then', 'our', '_Laws_,', 'master?', '', 'And', 'answered:', '', 'You', 'laws,', '', 'Yet', 'them.', '', 'Like', 'who', 'build', 'and', 'then', 'laughter.', '', 'But', 'the', 'ocean', 'shore,', '', 'And', 'ocean', 'laughs', 'you.', '', 'Verily', 'the', 'innocent.', '', 'But', 'not', 'an', 'not', 'sand-towers,', '', 'But', 'law', 'a', 'it', 'in', 'the', 'cripple', 'dancers?', '', 'What', 'and', 'deems', 'forest', 'stray', 'things?', '', 'What', 'shed', 'his', 'and', 'shameless?', '', 'And', 'the', 'wedding-feast,', 'and', 'tired', 'all', 'feasts', 'feasters', 'lawbreakers?', '', '*****', '', 'What', 'that', 'they', 'with', 'their', 'sun?', '', 'They', 'their', 'shadows', 'laws.', '', 'And', 'caster', 'of', 'shadows?', '', 'And', 'the', 'laws', 'their', 'shadows', 'earth?', '', 'But', 'what', 'images', 'hold', 'you?', '', 'You', 'what', 'weather-vane', 'course?', '', 'What', 'you', 'break', 'prison', 'door?', '', 'What', 'dance', 'but', 'iron', 'chains?', '', 'And', 'to', 'judgment', 'garment', 'yet', 'path?', '', '*****', '', 'People', 'the', 'drum,', 'strings', 'of', 'the', 'skylark', 'sing?', '', '*****', '*****', '', 'And', 'of', '_Freedom_.', '', 'And', 'answered:', '', 'At', 'fireside', 'I', 'and', 'worship', 'freedom,', '', 'Even', 'before', 'a', 'slays', 'them.', '', 'Ay,', 'in', 'the', 'seen', 'the', 'freedom', 'as', 'handcuff.', '', 'And', 'you', 'can', 'desire', 'of', 'harness', 'to', 'of', 'freedom', 'fulfilment.', '', 'You', 'yo

# Bonus Challenge

Rewrite the `word_filter` function above to not be case sensitive.

In [17]:
def word_filter_case(x):
   
    
            
        
    
    # your code here

SyntaxError: incomplete input (3937704105.py, line 7)

NameError: name 'words_eq' is not defined

# Challenge 3 - Reducing

#### Now that we have significantly cleaned up our text corpus, let's use the `reduce()` function to put the words back together into one long string separated by spaces. 

We will start by writing a function that takes two strings and concatenates them together with a space between the two strings.

In [18]:
def concat_space(a, b):
    '''
    Input:Two strings
    Output: A single string separated by a space
        
    Example:
    Input: 'John', 'Smith'
    Output: 'John Smith'
    '''

    reduced_string = a + " " +  b
    return reduced_string
    
    # your code here

In [19]:
concat_space("Hola,"," que tal")

'Hola,  que tal'

Use the function above to reduce the text corpus in the list `prophet_filter` into a single string. Assign this new string to the variable `prophet_string`.

In [20]:
# your code here
prophet_string = ''
for x in prophet_filter:
    prophet_string = concat_space(prophet_string,x)

In [21]:
print(prophet_string)

 Gibran  This most restrictions whatsoever. terms of at www.gutenberg.org. you'll have using this ebook.    Title: Prophet  Author: Gibran  Release #58585] Last 2018   Language: English  Character UTF-8  *** ***     Produced generously provided Archive   Transcriber's this utf-8 unencumbered with 58585-8.txt.        PROPHET  By Gibran  New Knopf  1923  _The Volume Are By Author_   “His reservoir of have been majesty with which own?”  --Claude Bragdon   GIBRAN  1919 1923 Sand of Man. Wanderer. Prophet 1933 Valley. 1948     CONTENTS   Ship.......7  Love.....................15  Marriage.................19  Children.................21  Giving...................23  Drinking......27  Work.....................31  Sorrow...........33  Houses...................37  Clothes..................41  Selling.......43  Punishment.....45  Laws.....................51  Freedom..................55  Passion.......57  Pain.....................60  Self-Knowledge...........62  Teaching.................64  Friendship...............66  Talking..................68  Time.....................70  Evil............72  Prayer...................76  Pleasure.................79  Beauty...................83  Religion.................87  Death....................90  Farewell................92     PROPHET  |Almustafa, beloved, own day, city of to return of his birth.  seventh day he climbed walls his ship mist.  Then flung open, sea. silences soul.  *****  But sadness came his heart:  How without sorrow? spirit Long were spent within nights depart from without regret?  Too I scattered many are walk naked cannot withdraw ache.  It this day, own hands.  Nor me, but with thirst.  *****  Yet longer.  her calls embark.  For in crystallize mould.  Fain is here. I?  Alone must ether.  eagle sun.  *****  Now hill, sea, harbour, mariners, land.  he said:  Sons of tides,  How dreams. which is dream.  Ready with sails wind.  Only in this look cast backward,  seafarer you, vast mother,  Who river stream,  Only stream make, glade,  boundless ocean.  *****  men their vineyards city gates.  his name, field telling his ship.  himself:  Shall of gathering?  in truth dawn?  has left to him his winepress? tree may gather them?  fountain cups?  Am mighty may breath may me?  what treasure I may confidence?  If what fields in what seasons?  If I lift flame that therein.  Empty lantern,  fill it also.  *****  These much in he himself deeper secret.  *****  [Illustration: 0020]  all they were one voice.  forth said:  Go us.  our twilight, us dreams dream.  No nor dearly beloved.  Suffer for your face.  *****  said unto him:  Let us now, our midst memory.  You spirit, light upon faces.  Much speechless was been veiled.  Yet would you.  knows not of separation.  *****  him. But bent his saw his breast.  towards temple.  woman she was seeress.  exceeding tenderness, first sought had been she saying:  Prophet uttermost, distances ship.  must needs go.  Deep of your place of love would hold you.  Yet that you your truth.  children, it shall perish.  In with our you have laughter sleep.  Now ourselves, shown you death.  *****  answered,  People I speak now moving souls?  ***** *****  Then of _Love_.  upon stillness upon he said:  When him,  Though steep.  to him,  Though his pinions you.  in him,  Though dreams as garden.  For shall he your growth pruning.  Even caresses branches that sun,  So shake earth.  *****  Like unto himself.  He naked.  He your husks.  He whiteness.  He pliant;  sacred fire, bread for feast.  *****  All you that your heart, fragment heart.  But only love’s pleasure,  Then you cover of love’s threshing-floor,  Into you shall your laughter, your tears.  *****  Love takes naught itself.  Love be possessed;  For love.  When “God is in God.”  course of you worthy, course.  Love fulfil itself.  But have desires, desires:  To that sings To know tenderness.  To understanding of love;  joyfully.  To give loving;  To meditate love’s ecstacy;  To with gratitude;  for of praise lips.  [Illustration: 0029]  ***** *****  Then said, master?  saying:  You you shall forevermore.  You white wings days.  Aye, silent God.  But your togetherness,  dance between you.  *****  Love of love:  Let between souls.  Fill from one cup.  Give eat not dance let each alone,  Even alone though music.  *****  Give each other’s keeping.  For contain your hearts.  near together:  For stand apart,  grow not shadow.  [Illustration: 0032]  ***** *****  babe against of _Children_.  said:  Your children.  They of Life’s itself.  They you,  they belong you.  *****  You your thoughts,  For thoughts.  You their souls,  For of tomorrow, not even dreams.  You seek not For life with yesterday.  You your children sent forth.  path of with His swift far.  Let be for gladness;  For that flies, is stable.  ***** *****  Then of _Giving_.  answered:  You of your possessions.  It you truly give.  For things you need them tomorrow?  bring to bones in pilgrims city?  need itself?  Is is full, unquenchable?  There much give it hidden desire unwholesome.  give all.  These is never empty.  There that reward.  pain, baptism.  know not seek joy, of virtue;  They myrtle breathes space.  Through God speaks, He smiles earth.  [Illustration: 0039]  It it is through understanding;  for one greater than giving.  withhold?  All given;  Therefore season of your inheritors’.  You only to deserving.”  so, nor pasture.  They to withhold perish.  Surely his days all else you.  from his cup stream.  be, than courage of receiving?  rend their pride, that their unabashed?  See to be giving.  For unto life--while giver, witness.  are all of gratitude, upon yourself gives.  Rather on his wings;  For is ito freehearted God for father.  [Illustration: 0042]  ***** *****  Then inn, Drinking_.  said:  Would fragrance air plant light.  But rob to quench act worship,  on which of forest that which innocent in man.  *****  When your heart,  “By too am consumed. For into my mightier hand.  Your but heaven.”  *****  your teeth, heart,  “Your body,  shall blossom heart,  breath, through all seasons.”  *****  gather winepress, heart,  “I shall be winepress,  in eternal vessels.”  wine, let song for cup;  remembrance for winepress.  ***** *****   Speak to _Work_.  saying:  You earth earth.  For stranger unto of life’s in majesty infinite.  When through whose hours turns music.  Which silent, in unison?  Always curse misfortune.  But you fulfil dream, assigned was born,  you are life,  be intimate secret.  *****  But affliction flesh I answer of your is written.  You is darkness, echo what weary.  darkness ‘save urge,  is knowledge,  when there work,  is love;  bind yourself one another, God.  *****  love?  It threads drawn your beloved cloth.  It affection, even in that house.  It reap if your fruit.  It fashion with spirit,  dead are watching.  Often if speaking in marble, own soul who ploughs seizes likeness who makes feet.”  But overwakefulness wind giant blades grass;  voice made sweeter loving.  *****  Work visible.  but only that you at of those joy.  For indifference, you but half hunger.  grapes, in as angels, you muffle day night.  ***** *****  Then of _Joy Sorrow_.  answered:  Your unmasked.  your laughter filled with tears.  be?  your being, contain.  Is very potter’s oven?  your spirit, hollowed with knives?  When your heart only that is giving joy.  When in your that in which has delight.  *****  Some than sorrow,” is greater.”  But are inseparable.  Together sits alone remember that bed.  Verily scales between joy.  Only at standstill balanced.  When to weigh needs must or fall.  ***** *****  Then said, Speak _Houses_.  said:  Build wilderness within walls.  For in your in you, alone.  Your body.  It stillness not dreamless. dream? grove or hilltop?  Would houses into scatter them meadow.  Would you might through vineyards, fragrance of garments.  But be.  In gathered you fear shall little longer separate your fields.  *****  what have it you doors?  Have that reveals power?  Have glimmering arches mind?  Have heart from stone to mountain?  Tell houses?  Or lust for that enters then becomes master?  *****  Ay, with hook your larger desires.  Though heart is iron.  It by your flesh.  It lays fragile vessels.  Verily murders walks grinning funeral.  But restless in nor tamed.  Your mast.  It that covers that guards eye.  You you may your heads ceiling, walls should down.  You dead living.  splendour, hold your longing.  For you abides whose door whose windows silences of night.  ***** *****  of _Clothes_.  answered:  Your your beauty, unbeautiful.  freedom them chain.  Would less of raiment,  For sunlight wind.  Some wind who wear.”  wind,  But softening thread.  in modesty is unclean.  more, what fouling mind?  delights to winds long hair.  ***** *****  of _Buying Selling_.  said:  To you how to hands.  It earth be satisfied.  Yet kindly to greed hunger.  When of meet gatherers spices,--  Invoke earth, sanctify reckoning that suffer take part would sell labour.  To say,  “Come with our your net;  For be bountiful us.”  *****  dancers of their also.  For frankincense, bring, though raiment soul.  place, see with empty hands.  For shall not wind till are satisfied.  ***** *****  Then city stood of _Crime Punishment_.  saying:  It wandering upon wind,  That commit unto yourself.  you knock gate blessed.  Like god-self;  It undefiled.  winged.  Even god-self;  It nor seeks serpent. But alone in being.  Much in you man,  But asleep in own awakening.  speak.  For nor crime crime.  *****  Oftentimes one who were not you world.  But righteous highest which you,  So fall lower you also.  yellow but whole cannot do you all.  Like together towards god-self.  [Illustration: 0064]  You wayfarers.  falls for against stone.  Ay, him, who yet removed stone.  heavy upon hearts:  for his murder,  being robbed.  deeds wicked,  doings felon.  Yea, victim of injured,  is guiltless unblamed.  You unjust wicked;  For face of together.  weaver cloth, also.  *****  If judgment wife,  Let her husband soul with measurements.  offender look offended.  name ax unto its roots;  good fruitless, in earth.  just,  What him who thief spirit?  What slays in spirit?  action is oppressor,  Yet outraged?  *****  whose remorse their misdeeds?  Is is administered you would serve?  Yet innocent of guilty.  Unbidden night, that upon themselves. would understand unless you fullness of light?  Only erect standing in his pigmy-self god-self, temple is in its foundation.  ***** *****  Then our _Laws_, master?  answered:  You laws,  Yet them.  Like who build then laughter.  But ocean shore,  ocean laughs you.  Verily innocent.  But not not sand-towers,  But law it in cripple dancers?  What deems forest stray things?  What shed his shameless?  wedding-feast, tired all feasts feasters lawbreakers?  *****  What that they with their sun?  They their shadows laws.  caster of shadows?  laws their shadows earth?  But what images hold you?  You what weather-vane course?  What you break prison door?  What dance but iron chains?  to judgment garment yet path?  *****  People drum, strings of skylark sing?  ***** *****  of _Freedom_.  answered:  At fireside I worship freedom,  Even before slays them.  Ay, in seen freedom as handcuff.  you can desire of harness to of freedom fulfilment.  You your days your nights grief,  But your life naked unbound.  *****  days chains your understanding your noon hour?  In is though its dazzle your eyes.  your own may become free?  If would abolish, your own forehead.  You law books of your sea upon them.  would dethrone, throne erected destroyed.  For their own own pride?  off, that rather than you.  dispel, heart feared.  *****  Verily being in desired cherished, which you escape.  These lights cling.  no more, shadow light.  its fetters greater freedom.  ***** *****  again Passion_.  saying:  Your battlefield, upon judgment wage your appetite.  Would in your discord into oneness melody.  But yourselves be lovers of elements?  Your rudder seafaring soul.  If be broken, drift, or in mid-seas. alone, is passion, unattended, its own destruction.  Therefore your reason it may sing;  with reason, live through resurrection, own ashes.  *****  I judgment two loved house.  Surely guest above more mindful faith both  Among cool sharing fields in silence, reason.”  mighty forest, majesty heart say passion.”  God’s sphere, you too in passion.  ***** *****  us of _Pain_.  said:  Your shell that understanding.  Even must break, sun, pain.  wonder at your pain than your joy;  your heart, accepted fields.  serenity through grief.  Much self-chosen.  It physician sick self.  Therefore drink his tranquillity: For is guided Unseen, burn your clay with His tears.  ***** *****  of _Self-Knowledge_.  saying:  Your secrets of nights.  But of your knowledge.  You you have thought.  You naked dreams.  should.  must needs sea;  depths would eyes.  But your unknown treasure;  your knowledge sounding line.  For measureless.  *****  Say but rather, truth.”  Say soul.” soul walking path.”  For paths.  neither does reed.  of countless petals.  [Illustration: 0083]  ***** *****  Then of _Teaching_.  said:  “No that which dawning knowledge.  of gives not his faith lovingness.  If bid you but rather of your mind.  his understanding cannot give understanding.  rhythm he cannot arrests it. science of regions of cannot conduct thither.  For its wings man.  alone in of you in earth.  ***** *****  of _Friendship_.  saying:  Your answered.  He love thanksgiving.  fireside.  For hunger, peace.  When you fear nor do “ay.”  ceases not heart;  For all thoughts, expectations are is unacclaimed.  When you grieve not;  For him may mountain clearer from no purpose deepening of spirit.  For disclosure not love unprofitable caught.  *****  friend.  If tide, let also.  For should seek kill?  Seek live.  For not your emptiness.  friendship let of pleasures.  For things is refreshed.  ***** *****  of _Talking_.  saying:  You peace with thoughts;  solitude your lips, pastime.  is half murdered.  For in its wings fly.  There talkative alone.  to their they would escape.  without reveal not understand.  truth within in words.  In spirit dwells silence.  *****  When roadside spirit direct your tongue.  Let to ear;  For of your is remembered  When vessel more.  ***** *****  what of _Time_?  answered:  You measureless immeasurable.  You even spirit according seasons.  Of upon whose its flowing.  Yet of life’s timelessness,  today’s memory dream.  contemplates dwelling within moment which space. Who his power boundless?  very love, encompassed within moving love thought, other love deeds?  is, undivided paceless?  *****  But measure time season encircle seasons,  with remembrance longing.  ***** *****  city said, Evil_.  answered:  Of not of evil.  For by its thirst?  Verily food even thirsts it waters.  You with yourself.  Yet yourself you evil.  For of thieves; house.  wander aimlessly sink not when you yourself.  Yet gain for yourself.  For are but sucks breast.  Surely root, “Be ever giving abundance.”  For as receiving root.  *****  You in your speech,  Yet sleep while without purpose.  strengthen tongue.  You goal firmly steps.  Yet thither limping. not backward.  But see that lame, deeming kindness.  *****  You you are good,  You sluggard.  Pity teach swiftness turtles.  In lies your in all you.  But torrent sea, carrying hillsides forest.  that loses lingers shore.  But to him are you halting?”  For naked, “Where houseless, your house?”  ***** *****  Then us of _Prayer_.  saying:  You your need; also in your days abundance.  For of yourself ether?  pour your for your dawning of heart.  your soul should spur though weeping, laughing.  When air very hour, you may meet.  Therefore temple invisible sweet communion.  For for no shall not receive:  to humble lifted:  Or to beg not be heard.  It temple invisible.  *****  I words.  God when He your lips.  seas mountains. But mountains seas can heart,  stillness of saying in silence,  “Our is thy willeth.  It desireth.  It our nights, which are also.  We thou knowest born in us:  Thou more of all.”  [Illustration: 0100]  ***** *****  Then city once Speak to _Pleasure_.  saying:  Pleasure freedom-song,  But freedom.  It desires,  But fruit.  It height,  But high.  It wing,  But encompassed.  Ay, freedom-song.  with fullness have you singing.  Some if it rebuked. nor rebuke seek.  For not her alone;  Seven of them pleasure.  Have was digging found treasure?  *****  remember pleasures wrongs committed drunkenness.  But mind chastisement.  They pleasures with harvest summer.  Yet let them comforted.  who are to remember;  remembering pleasures, lest offend against it.  But their pleasure.  though they hands.  But offend spirit?  Shall stillness firefly stars?  smoke burden wind?  Think pool which staff?  *****  Oftentimes pleasure you recesses being.  Who omitted today, tomorrow?  Even heritage be deceived.  soul,  sweet music sounds.  *****  “How shall is good not good?”  Go you pleasure of flower,  But flower bee.  For of life,  messenger of love,  giving need ecstasy.  People your pleasures bees.  ***** *****  of _Beauty_.  answered:  Where how shall be your guide?  except she speech?  say, “Beauty gentle.  Like own glory us.”  is dread.  Like earth beneath us.”  is of our spirit. our silences quivers in shadow.”  But her shouting mountains,  of hoofs, roaring lions.”  At say, “Beauty from east.”  wayfarers leaning over sunset.”  *****  In shall come hills.”  reapers say, autumn of snow things have beauty,  Yet of needs unsatisfied,  ecstasy.  It empty hand forth,  But soul enchanted.  It nor hear,  But you close hear though ears.  It furrowed bark, claw,  But bloom in flight.  *****  People when life face.  But veil. Beauty itself in mirror.  But mirror.  ***** *****  us of _Religion_.  said:  Have else?  Is all reflection,  nor reflection, surprise ever while loom?  Who from his his occupations?  Who him, saving, for myself; other for body?”  All beat through He who best garment naked.  holes in skin.  ethics imprisons cage.  bars wires.  window, to yet visited whose windows dawn.  *****  Your your religion.  Whenever you your all.  Take mallet lute,  in necessity delight.  For your achievements your failures.  in adoration than their lower than despair.  *****  not therefore riddles.  Rather see Him children.  Him walking His arms in rain.  You flowers, then in trees.  ***** *****  Then would ask _Death_.  said:  You death.  But you seek life?  blind unto mystery of light.  If spirit of body life.  For river one.  In desires lies beyond;  snow your spring.  Trust hidden fear of shepherd king whose in honour.  Is his trembling, mark of king?  Yet his trembling?  *****  For naked in sun?  but to restless tides, seek unencumbered?  Only of silence sing.  mountain top, climb.  your limbs, dance. evening.  be this spirit that spoken.  Was I listener?  *****  Then Temple him. upon deck.  raised his said:  People me leave you.  Less I must go.  We lonelier way, ended another us where earth travel.  We tenacious plant, our fullness to scattered.  *****  Brief briefer spoken.  But ears, then I again,  more yielding speak.  Yea, tide,  greater again will understanding.  seek.  If that truth clearer voice, your thoughts.  I of Orphalese, emptiness; fulfilment of it be day.  Man’s love, nor should satisfy needs.  Know greater silence return.  dawn, leaving shall rise then fall rain.  been.  In have walked spirit has houses,  heart, I knew all.  Ay, pain, my dreams.  lake among mountains.  I bending passing your desires.  laughter of longing rivers.  streams to sing.  [Illustration: 0119]  But greater me.  It you;  but cells sinews;  He is but throbbing.  It vast,  you you.  For that are sphere?  What what presumptions flight?  Like apple blossoms His might his fragrance in his deathless.  *****  You chain, weakest link.  This also as link.  To deed is frailty foam.  To to cas

# Challenge 4 - Applying Functions to DataFrames

#### Our next step is to use the apply function to a dataframe and transform all cells.

To do this, we will connect to Ironhack's database and retrieve the data from the *pollution* database. Select the *beijing_pollution* table and retrieve its data.

In [31]:
# your code here
pollution = pd.read_csv(".\PRSA_data_2010.1.1-2014.12.31.csv")
pollution

,No,year,month,day,hour,pm2.5,DEWP,TEMP,PRES,cbwd,Iws,Is,Ir
0,1,2010,1,1,0,NaN,-21,-11.0,1021.0,NW,1.79,0,0
1,2,2010,1,1,1,NaN,-21,-12.0,1020.0,NW,4.92,0,0
2,3,2010,1,1,2,NaN,-21,-11.0,1019.0,NW,6.71,0,0
3,4,2010,1,1,3,NaN,-21,-14.0,1019.0,NW,9.84,0,0
4,5,2010,1,1,4,NaN,-20,-12.0,1018.0,NW,12.97,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43819,43820,2014,12,31,19,8.0,-23,-2.0,1034.0,NW,231.97,0,0
43820,43821,2014,12,31,20,10.0,-22,-3.0,1034.0,NW,237.78,0,0
43821,43822,2014,12,31,21,10.0,-22,-3.0,1034.0,NW,242.70,0,0
43822,43823,2014,12,31,22,8.0,-22,-4.0,1034.0,NW,246.72,0,0
43823,43824,2014,12,31,23,12.0,-21,-3.0,1034.0,NW,249.85,0,0

Let's look at the data using the `head()` function.

In [32]:
# your code here
pollution.head()

   No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

The next step is to create a function that divides a cell by 24 to produce an hourly figure. Write the function below.

In [24]:
def hourly(x):
    '''
    Input: A numerical value
    Output: The value divided by 24
        
    Example:
    Input: 48
    Output: 2.0
    '''
    result = x / 24

    return result

    
    
    # your code here

Apply this function to the columns `Iws`, `Is`, and `Ir`. Store this new dataframe in the variable `pm25_hourly`.

In [38]:
# your code here
pollution["Iws"] = pollution["Iws"].apply(hourly)
pollution["Is"] = pollution["Is"].apply(hourly)
pollution["Ir"] = pollution["Ir"].apply(hourly)
pm25_hourly = pd.concat([pollution["Iws"],pollution["Is"],pollution["Ir"]],axis=1)
pm25_hourly

                Iws   Is   Ir
0      9.366678e-09  0.0  0.0
1      2.574528e-08  0.0  0.0
2      3.511196e-08  0.0  0.0
3      5.149056e-08  0.0  0.0
4      6.786917e-08  0.0  0.0
...             ...  ...  ...
43819  1.213848e-06  0.0  0.0
43820  1.244251e-06  0.0  0.0
43821  1.269996e-06  0.0  0.0
43822  1.291032e-06  0.0  0.0
43823  1.307410e-06  0.0  0.0

[43824 rows x 3 columns]

In [39]:
pm25_hourly.head()

            Iws   Is   Ir
0  9.366678e-09  0.0  0.0
1  2.574528e-08  0.0  0.0
2  3.511196e-08  0.0  0.0
3  5.149056e-08  0.0  0.0
4  6.786917e-08  0.0  0.0

#### Our last challenge will be to create an aggregate function and apply it to a select group of columns in our dataframe.

Write a function that returns the standard deviation of a column divided by the length of a column minus 1. Since we are using pandas, do not use the `len()` function. One alternative is to use `count()`. Also, use the numpy version of standard deviation.

In [ ]:
def sample_sd(x):
    '''
    Input: A Pandas series of values
    Output: the standard deviation divided by the number of elements in the series
        
    Example:
    Input: pd.Series([1,2,3,4])
    Output: 0.3726779962
    '''
    
    # your code here